// 完整地点数据（约121个，含经纬度）
// ==================== 完整地点数据（基于Excel，包含type和desc） ====================
const locations = [
    { id: "L001", name: "上海", country: "中国", province: "上海市", city: "上海", lat: 31.2304, lng: 121.4737, historical_name: "", location_description: "", type: "长期居住", desc: "斯诺1928年抵华首站，亲历一·二八事变和淞沪会战。" },
    { id: "L002", name: "北京", country: "中国", province: "北京市", city: "北京", lat: 39.9042, lng: 116.4074, historical_name: "北平", location_description: "历史地名北平，中国重要地点", type: "长期居住", desc: "燕京大学任教，参与一二·九学生运动，见证卢沟桥事变。" },
    { id: "L003", name: "陕北革命根据地", country: "中国", province: "陕西省", city: "延安市", lat: 36.5, lng: 109, historical_name: "", location_description: "陕北地区重要地点", type: "重大事件", desc: "中共中央所在地，斯诺红区之行的核心区域。" },
    { id: "L004", name: "萨拉齐", country: "中国", province: "内蒙古自治区", city: "包头市（土默特右旗）", lat: 40.56, lng: 110.53, historical_name: "Saratsi", location_description: "历史地名Saratsi，中国重要地点", type: "重大事件", desc: "1929年西北大饥荒重灾区，斯诺觉醒点，写下《拯救二十五万生灵》。" },
    { id: "L005", name: "纽约", country: "美国", province: "纽约州", city: "纽约市", lat: 40.7128, lng: -74.006, historical_name: "", location_description: "", type: "途经", desc: "斯诺出生地，记者生涯起点。" },
    { id: "L006", name: "中国", country: "中国", province: "", city: "", lat: 35, lng: 105, historical_name: "", location_description: "", type: "其他", desc: "广义中国范围。" },
    { id: "L007", name: "南京", country: "中国", province: "江苏省", city: "南京", lat: 32.0603, lng: 118.7969, historical_name: "金陵", location_description: "历史地名金陵，中国重要地点", type: "途经", desc: "国民政府首都，斯诺采访蒋介石，报道国民党政治。" },
    { id: "L008", name: "哈尔滨", country: "中国", province: "黑龙江省", city: "哈尔滨", lat: 45.8038, lng: 126.5349, historical_name: "", location_description: "", type: "途经", desc: "东北重镇，斯诺前往采访中东路事件。" },
    { id: "L009", name: "沈阳", country: "中国", province: "辽宁省", city: "沈阳", lat: 41.8057, lng: 123.4315, historical_name: "奉天", location_description: "历史地名奉天，中国重要地点", type: "重大事件", desc: "九一八事变爆发地，斯诺在《远东前线》中详述。" },
    { id: "L010", name: "绥远", country: "中国", province: "内蒙古自治区", city: "呼和浩特市", lat: 40.8, lng: 111.7, historical_name: "绥远省", location_description: "历史地名绥远省，中国重要地点", type: "途经", desc: "即今呼和浩特，斯诺1929年考察饥荒地区。" },
    { id: "L011", name: "扬州", country: "中国", province: "江苏省", city: "扬州", lat: 32.3939, lng: 119.4128, historical_name: "", location_description: "", type: "途经", desc: "京杭大运河沿岸城市，斯诺旅行经过。" },
    { id: "L012", name: "西北", country: "中国", province: "（泛指西北）", city: "", lat: 37, lng: 104, historical_name: "", location_description: "西北地区重要地点", type: "途经", desc: "中国西北地区，斯诺多次旅行考察。" },
    { id: "L013", name: "朝鲜", country: "朝鲜", province: "", city: "", lat: 39, lng: 125.7, historical_name: "", location_description: "", type: "途经", desc: "日本殖民地，斯诺旅行经过。" },
    { id: "L014", name: "张家口", country: "中国", province: "河北省", city: "张家口市", lat: 40.8108, lng: 114.8794, historical_name: "", location_description: "", type: "途经", desc: "华北门户，斯诺进入绥远前的最后一站。" },
    { id: "L015", name: "波斯", country: "伊朗", province: "", city: "", lat: 32, lng: 53, historical_name: "波斯帝国", location_description: "历史地名波斯帝国，伊朗重要地点", type: "途经", desc: "今伊朗，斯诺旅行计划中的一站（未实际到达）。" },
    { id: "L016", name: "归化", country: "中国", province: "内蒙古自治区", city: "呼和浩特市", lat: 40.8425, lng: 111.7495, historical_name: "今呼和浩特市", location_description: "历史地名今呼和浩特市，中国重要地点", type: "途经", desc: "今呼和浩特，斯诺考察饥荒时的停留点。" },
    { id: "L017", name: "黄河", country: "中国", province: "（流经多省）", city: "", lat: 35, lng: 105, historical_name: "", location_description: "", type: "途经", desc: "中国第二大河，斯诺多次渡河。" },
    { id: "L018", name: "长城", country: "中国", province: "（跨多省）", city: "", lat: 40.4319, lng: 116.5704, historical_name: "", location_description: "", type: "途经", desc: "中国象征，斯诺多次经过八达岭等关隘。" },
    { id: "L019", name: "美国", country: "美国", province: "", city: "", lat: 37.1, lng: -98.5, historical_name: "", location_description: "", type: "其他", desc: "斯诺祖国，1928年离开，1941年返回。" },
    { id: "L020", name: "日本", country: "日本", province: "", city: "", lat: 36.2, lng: 138.2, historical_name: "", location_description: "", type: "途经", desc: "斯诺赴华途中经过，后多次采访。" },
    { id: "L021", name: "东北", country: "中国", province: "（黑吉辽）", city: "", lat: 44, lng: 125, historical_name: "满洲", location_description: "历史地名满洲，中国重要地点", type: "途经", desc: "满洲地区，九一八事变后被日军占领。" },
    { id: "L022", name: "莫斯科", country: "苏联", province: "", city: "莫斯科", lat: 55.7558, lng: 37.6173, historical_name: "", location_description: "", type: "途经", desc: "苏联首都，斯诺曾计划访问。" },
    { id: "L023", name: "西伯利亚", country: "苏联", province: "", city: "", lat: 60, lng: 105, historical_name: "", location_description: "", type: "途经", desc: "亚欧大陆北部，斯诺计划经此返回美国。" },
    { id: "L024", name: "公共租界", country: "中国", province: "上海市", city: "上海", lat: 31.2333, lng: 121.4867, historical_name: "International Settlement", location_description: "历史地名International Settlement，中国重要地点", type: "长期居住", desc: "上海国际公共租界，斯诺早期工作地，《密勒氏评论报》所在地。" },
    { id: "L025", name: "法国租界", country: "中国", province: "上海市", city: "上海", lat: 31.2167, lng: 121.4733, historical_name: "French Concession", location_description: "历史地名French Concession，中国重要地点", type: "长期居住", desc: "上海法租界，宋庆龄住所所在地。" },
    { id: "L026", name: "塞班岛", country: "美国（北马里亚纳群岛）", province: "", city: "", lat: 15.19, lng: 145.7455, historical_name: "", location_description: "", type: "其他", desc: "太平洋岛屿，二战战场，卡尔逊在此负伤。" },
    { id: "L027", name: "龙华", country: "中国", province: "上海市", city: "上海", lat: 31.1559, lng: 121.4354, historical_name: "", location_description: "", type: "重大事件", desc: "上海龙华警备司令部，国民党处决政治犯之地。" },
    { id: "L028", name: "俄国", country: "俄罗斯", province: "", city: "", lat: 55.7558, lng: 37.6173, historical_name: "", location_description: "", type: "途经", desc: "苏联，斯诺曾申请签证。" },
    { id: "L029", name: "亚洲", country: "（洲际）", province: "", city: "", lat: 30, lng: 100, historical_name: "", location_description: "", type: "其他", desc: "广义亚洲大陆。" },
    { id: "L030", name: "欧洲", country: "（洲际）", province: "", city: "", lat: 50, lng: 15, historical_name: "", location_description: "", type: "其他", desc: "广义欧洲大陆。" },
    { id: "L031", name: "印度", country: "印度", province: "", city: "", lat: 20.6, lng: 78.9, historical_name: "", location_description: "", type: "途经", desc: "斯诺1931年访问，会见甘地、尼赫鲁。" },
    { id: "L032", name: "马达加斯加", country: "马达加斯加", province: "", city: "", lat: 20, lng: 47, historical_name: "", location_description: "", type: "途经", desc: "斯诺旅行计划中的一站。" },
    { id: "L033", name: "东京", country: "日本", province: "东京都", city: "东京", lat: 35.6762, lng: 139.6503, historical_name: "", location_description: "", type: "途经", desc: "日本首都，斯诺1932年在此结婚。" },
    { id: "L034", name: "台湾", country: "中国", province: "台湾省", city: "", lat: 23.7, lng: 121, historical_name: "", location_description: "", type: "途经", desc: "日本殖民地，斯诺1930年访问。" },
    { id: "L035", name: "广州", country: "中国", province: "广东省", city: "广州市", lat: 23.1291, lng: 113.2644, historical_name: "", location_description: "广东省地区重要地点", type: "途经", desc: "华南最大城市，斯诺考察国民党统治。" },
    { id: "L036", name: "广东省", country: "中国", province: "广东省", city: "", lat: 23.1, lng: 113.3, historical_name: "", location_description: "", type: "途经", desc: "华南省份，斯诺旅行经过。" },
    { id: "L037", name: "檀香山", country: "美国", province: "夏威夷州", city: "檀香山", lat: 21.3069, lng: -157.8583, historical_name: "Honolulu", location_description: "历史地名Honolulu，美国重要地点", type: "途经", desc: "夏威夷首府，斯诺1928年在此逗留。" },
    { id: "L038", name: "香港", country: "中国", province: "香港特别行政区", city: "香港", lat: 22.3193, lng: 114.1694, historical_name: "", location_description: "中国地区重要地点", type: "途经", desc: "英国殖民地，斯诺1941年离开中国的最后一站。" },
    { id: "L039", name: "沙面", country: "中国", province: "广东省", city: "广州市", lat: 23.1154, lng: 113.2403, historical_name: "", location_description: "", type: "途经", desc: "广州租界岛，外国领事馆所在地。" },
    { id: "L040", name: "苏联", country: "苏联", province: "", city: "", lat: 55.7558, lng: 37.6173, historical_name: "", location_description: "", type: "途经", desc: "苏维埃社会主义共和国联盟。" },
    { id: "L041", name: "云南", country: "中国", province: "云南省", city: "", lat: 24, lng: 102.5, historical_name: "", location_description: "边远的高原地区", type: "途经", desc: "中国西南边远高原地区，斯诺1931年旅行。" },
    { id: "L042", name: "昆明", country: "中国", province: "云南省", city: "昆明", lat: 25.0389, lng: 102.7183, historical_name: "", location_description: "云南地区重要地点", type: "途经", desc: "云南省会，斯诺访问，见识军阀暴行。" },
    { id: "L043", name: "缅甸", country: "缅甸", province: "", city: "", lat: 19, lng: 96.5, historical_name: "", location_description: "", type: "途经", desc: "英国殖民地，斯诺1931年从云南步行进入。" },
    { id: "L044", name: "印度支那", country: "印度支那", province: "", city: "", lat: 15, lng: 107, historical_name: "", location_description: "", type: "途经", desc: "今越南、老挝、柬埔寨，法国殖民地。" },
    { id: "L045", name: "西藏", country: "中国", province: "西藏自治区", city: "", lat: 31.7, lng: 88.1, historical_name: "", location_description: "西藏地区重要地点", type: "途经", desc: "青藏高原，斯诺曾远眺。" },
    { id: "L046", name: "法国", country: "法国", province: "", city: "巴黎", lat: 46.2, lng: 2.2, historical_name: "", location_description: "", type: "途经", desc: "欧洲国家，斯诺在印度支那接触到法国殖民者。" },
    { id: "L047", name: "德国", country: "德国", province: "", city: "柏林", lat: 51.1, lng: 10.4, historical_name: "", location_description: "", type: "途经", desc: "纳粹德国，斯诺批判其法西斯主义。" },
    { id: "L048", name: "波兰", country: "波兰", province: "", city: "华沙", lat: 51.9, lng: 19.1, historical_name: "", location_description: "", type: "途经", desc: "欧洲国家，苏联与德国瓜分。" },
    { id: "L049", name: "河内", country: "越南", province: "", city: "河内", lat: 21.0285, lng: 105.8542, historical_name: "", location_description: "", type: "途经", desc: "法属印度支那首府，斯诺访问。" },
    { id: "L050", name: "孟加拉湾", country: "（印度洋）", province: "", city: "", lat: 15, lng: 88, historical_name: "", location_description: "", type: "途经", desc: "印度洋海湾，斯诺曾航行经过。" },
    { id: "L051", name: "舍资", country: "中国", province: "云南省", city: "", lat: 25.19, lng: 101.91, historical_name: "", location_description: "云南地区重要地点", type: "途经", desc: "云南小村，斯诺旅行经过。" },
    { id: "L052", name: "禄丰", country: "中国", province: "云南省", city: "楚雄彝族自治州", lat: 25.1278, lng: 102.0783, historical_name: "", location_description: "云南地区重要地点", type: "途经", desc: "云南县，斯诺旅行经过。" },
    { id: "L053", name: "山东", country: "中国", province: "山东省", city: "", lat: 36.3, lng: 117.1, historical_name: "", location_description: "山东省地区重要地点", type: "途经", desc: "中国东部省份，斯诺经过。" },
    { id: "L054", name: "广西", country: "中国", province: "广西壮族自治区", city: "", lat: 23.7, lng: 108.3, historical_name: "", location_description: "广西地区重要地点", type: "途经", desc: "中国南部省份，军阀混战地区。" },
    { id: "L055", name: "个旧", country: "中国", province: "云南省", city: "红河哈尼族彝族自治州", lat: 23.36, lng: 103.16, historical_name: "", location_description: "云南地区重要地点", type: "途经", desc: "云南锡矿中心，童工劳动惨状。" },
    { id: "L056", name: "大理", country: "中国", province: "云南省", city: "大理白族自治州", lat: 25.6065, lng: 100.2679, historical_name: "", location_description: "云南地区重要地点", type: "途经", desc: "云南古城，斯诺旅行住宿地。" },
    { id: "L057", name: "闸北", country: "中国", province: "上海市", city: "上海", lat: 31.2566, lng: 121.4597, historical_name: "", location_description: "", type: "重大事件", desc: "上海华界，一·二八事变主战场。" },
    { id: "L058", name: "上海北站", country: "中国", province: "上海市", city: "上海", lat: 31.259, lng: 121.453, historical_name: "", location_description: "", type: "重大事件", desc: "一·二八事变中日军袭击目标。" },
    { id: "L059", name: "热河", country: "中国", province: "（今辽冀蒙交界）", city: "", lat: 41.6, lng: 118, historical_name: "", location_description: "", type: "途经", desc: "原省份，1933年被日军占领。" },
    { id: "L060", name: "罗马", country: "意大利", province: "", city: "罗马", lat: 41.9028, lng: 12.4964, historical_name: "", location_description: "", type: "途经", desc: "意大利首都，墨索里尼统治。" },
    { id: "L061", name: "柏林", country: "德国", province: "", city: "柏林", lat: 52.52, lng: 13.405, historical_name: "", location_description: "", type: "途经", desc: "德国首都，纳粹中心。" },
    { id: "L062", name: "东交民巷", country: "中国", province: "北京市", city: "北京", lat: 39.9036, lng: 116.3986, historical_name: "使馆区", location_description: "历史地名使馆区，中国重要地点", type: "长期居住", desc: "北京使馆区，外国势力象征。" },
    { id: "L063", name: "海淀", country: "中国", province: "北京市", city: "北京", lat: 40.0311, lng: 116.3065, historical_name: "", location_description: "", type: "长期居住", desc: "北京西郊，斯诺夫妇1934-1935年居住地。" },
    { id: "L064", name: "西山", country: "中国", province: "北京市", city: "北京", lat: 39.96, lng: 116.18, historical_name: "", location_description: "", type: "途经", desc: "北京西郊，斯诺夫妇郊游地。" },
    { id: "L065", name: "颐和园", country: "中国", province: "北京市", city: "北京", lat: 40.0007, lng: 116.275, historical_name: "", location_description: "", type: "途经", desc: "北京皇家园林，斯诺参观。" },
    { id: "L066", name: "华北", country: "中国", province: "华北地区", city: "", lat: 39.5, lng: 116, historical_name: "", location_description: "中国北方地区重要地点", type: "途经", desc: "中国北方，日本侵略目标。" },
    { id: "L067", name: "天津", country: "中国", province: "天津市", city: "天津", lat: 39.0842, lng: 117.201, historical_name: "", location_description: "", type: "途经", desc: "华北重要港口，斯诺多次经停。" },
    { id: "L068", name: "长江流域", country: "中国", province: "（流域区）", city: "", lat: 30, lng: 115, historical_name: "", location_description: "", type: "途经", desc: "中国经济核心区，斯诺多次旅行。" },
    { id: "L069", name: "天安门广场", country: "中国", province: "北京市", city: "北京", lat: 39.9087, lng: 116.3975, historical_name: "", location_description: "", type: "途经", desc: "北京中心，一二·九游行集会地。" },
    { id: "L070", name: "紫禁城", country: "中国", province: "北京市", city: "北京", lat: 39.9163, lng: 116.3972, historical_name: "故宫", location_description: "历史地名故宫，中国重要地点", type: "途经", desc: "明清皇宫，北京象征。" },
    { id: "L071", name: "汉口", country: "中国", province: "湖北省", city: "武汉", lat: 30.5963, lng: 114.3015, historical_name: "", location_description: "", type: "途经", desc: "武汉三镇之一，抗战初期工合总部所在地。" },
    { id: "L072", name: "华南", country: "中国", province: "华南地区", city: "", lat: 23, lng: 113, historical_name: "", location_description: "华南地区重要地点", type: "途经", desc: "中国南部，斯诺早期旅行。" },
    { id: "L073", name: "海淀区", country: "中国", province: "北京市", city: "北京市", lat: 40.0311, lng: 116.3065, historical_name: "", location_description: "", type: "长期居住", desc: "北京市海淀区，斯诺居住地（同L063）。" },
    { id: "L074", name: "英国", country: "英国", province: "", city: "伦敦", lat: 51.5074, lng: -0.1278, historical_name: "", location_description: "", type: "其他", desc: "英国，斯诺评论其帝国主义政策。" },
    { id: "L075", name: "西安", country: "中国", province: "陕西省", city: "西安", lat: 34.3416, lng: 108.9398, historical_name: "长安", location_description: "历史地名长安，中国重要地点", type: "重大事件", desc: "西安事变发生地，斯诺进入红区的咽喉，与张学良会面。" },
    { id: "L076", name: "保安", country: "中国", province: "陕西省", city: "延安市（志丹县）", lat: 36.8236, lng: 108.772, historical_name: "今志丹县", location_description: "一个一度相当大的边塞城市的废墟", type: "重大事件", desc: "今陕西志丹县，1936年斯诺采访毛泽东的窑洞，红区首府。" },
    { id: "L077", name: "红区", country: "中国", province: "陕西省", city: "延安市", lat: 36.5, lng: 109, historical_name: "苏区", location_description: "共产党领导的区域", type: "重大事件", desc: "共产党领导的陕甘宁苏区。" },
    { id: "L078", name: "延安", country: "中国", province: "陕西省", city: "延安", lat: 36.5853, lng: 109.4898, historical_name: "肤施", location_description: "历史地名肤施，中国重要地点", type: "重大事件", desc: "红色首都，斯诺1939年重访与毛泽东长谈。" },
    { id: "L079", name: "安塞", country: "中国", province: "陕西省", city: "延安市", lat: 36.8637, lng: 109.3284, historical_name: "", location_description: "陕北地区重要地点", type: "途经", desc: "陕北县，斯诺进入苏区第一站。" },
    { id: "L080", name: "洛川", country: "中国", province: "陕西省", city: "延安市", lat: 35.7632, lng: 109.432, historical_name: "", location_description: "陕北地区重要地点", type: "途经", desc: "陕北县，斯诺经过。" },
    { id: "L081", name: "陕北", country: "中国", province: "陕西省", city: "延安市", lat: 36.6, lng: 109.1, historical_name: "", location_description: "陕北地区重要地点", type: "途经", desc: "陕西北部，红军根据地。" },
    { id: "L082", name: "苏区", country: "中国", province: "陕西省", city: "延安市", lat: 36.5, lng: 109, historical_name: "", location_description: "西北地区重要地点", type: "重大事件", desc: "苏维埃控制区域。" },
    { id: "L083", name: "甘肃", country: "中国", province: "甘肃省", city: "", lat: 35.7, lng: 103.8, historical_name: "", location_description: "西北地区重要地点", type: "途经", desc: "西北省份，斯诺西部前线访问地。" },
    { id: "L084", name: "宁夏", country: "中国", province: "宁夏回族自治区", city: "", lat: 37.5, lng: 106.3, historical_name: "", location_description: "西北地区重要地点", type: "途经", desc: "西北省份，斯诺旅行。" },
    { id: "L085", name: "西北红区", country: "中国", province: "陕西/甘肃", city: "", lat: 36, lng: 106, historical_name: "", location_description: "西北地区重要地点", type: "重大事件", desc: "陕甘宁边区。" },
    { id: "L086", name: "江西苏区", country: "中国", province: "江西省", city: "赣州市", lat: 25.8, lng: 114.9, historical_name: "", location_description: "江西地区重要地点", type: "途经", desc: "中央苏区所在地，斯诺未能访问。" },
    { id: "L087", name: "绥远省", country: "中国", province: "内蒙古自治区", city: "", lat: 40.8, lng: 111.7, historical_name: "", location_description: "", type: "途经", desc: "旧省名，今内蒙古中部。" },
    { id: "L088", name: "四川", country: "中国", province: "四川省", city: "", lat: 30, lng: 102.7, historical_name: "", location_description: "中国西南地区重要地点", type: "途经", desc: "西南省份，军阀割据。" },
    { id: "L089", name: "陕西", country: "中国", province: "陕西省", city: "", lat: 34.2667, lng: 108.95, historical_name: "", location_description: "中国地区重要地点", type: "途经", desc: "西北省份，红军根据地。" },
    { id: "L090", name: "南苑", country: "中国", province: "北京市", city: "北京", lat: 39.7897, lng: 116.3793, historical_name: "", location_description: "", type: "途经", desc: "北京南郊，七七事变战场。" },
    { id: "L091", name: "英国租界", country: "中国", province: "天津市", city: "天津", lat: 39.1358, lng: 117.2193, historical_name: "", location_description: "", type: "途经", desc: "天津英租界，斯诺经过。" },
    { id: "L092", name: "波罗底诺", country: "俄国", province: "", city: "", lat: 55.5, lng: 35.5, historical_name: "Borodino", location_description: "历史地名Borodino，俄国重要地点", type: "其他", desc: "俄国村庄，拿破仑战争战场，斯诺类比。" },
    { id: "L093", name: "青岛", country: "中国", province: "山东省", city: "青岛市", lat: 36.0671, lng: 120.3826, historical_name: "", location_description: "", type: "途经", desc: "山东港口，斯诺蜜月旅行地。" },
    { id: "L094", name: "重庆", country: "中国", province: "重庆市", city: "重庆", lat: 29.563, lng: 106.5516, historical_name: "", location_description: "", type: "途经", desc: "战时陪都，斯诺报道国民党腐败与皖南事变真相。" },
    { id: "L095", name: "南市", country: "中国", province: "上海市", city: "上海", lat: 31.2168, lng: 121.4804, historical_name: "", location_description: "", type: "途经", desc: "上海华界南部。" },
    { id: "L096", name: "尼加拉瓜", country: "尼加拉瓜", province: "", city: "", lat: 12.8, lng: -85.2, historical_name: "", location_description: "", type: "其他", desc: "中美洲国家，桑地诺游击队。" },
    { id: "L097", name: "西北地区", country: "中国", province: "（泛指西北）", city: "", lat: 37, lng: 104, historical_name: "", location_description: "西北地区重要地点", type: "途经", desc: "同L012。" },
    { id: "L098", name: "租界", country: "中国", province: "上海市", city: "上海", lat: 31.2304, lng: 121.46, historical_name: "", location_description: "", type: "长期居住", desc: "泛指上海租界。" },
    { id: "L099", name: "菲律宾", country: "菲律宾", province: "", city: "", lat: 13, lng: 122, historical_name: "", location_description: "", type: "途经", desc: "美国殖民地，斯诺1938-1940年居住地。" },
    { id: "L100", name: "马尼拉", country: "菲律宾", province: "", city: "马尼拉", lat: 14.5995, lng: 120.9842, historical_name: "", location_description: "", type: "途经", desc: "菲律宾首都，斯诺为工合筹款。" },
    { id: "L101", name: "福建省", country: "中国", province: "福建省", city: "", lat: 26.1, lng: 119.3, historical_name: "", location_description: "", type: "途经", desc: "东南沿海，十九路军起义地。" },
    { id: "L102", name: "碧瑶", country: "菲律宾", province: "", city: "碧瑶", lat: 16.4023, lng: 120.596, historical_name: "", location_description: "", type: "途经", desc: "菲律宾北部山地，斯诺写作地。" },
    { id: "L103", name: "北吕宋", country: "菲律宾", province: "", city: "", lat: 18, lng: 121, historical_name: "", location_description: "", type: "途经", desc: "菲律宾北部，斯诺旅行。" },
    { id: "L104", name: "浅水湾", country: "中国", province: "香港特别行政区", city: "香港", lat: 22.2405, lng: 114.1979, historical_name: "", location_description: "", type: "途经", desc: "香港海滩，斯诺夫妇度假地。" },
    { id: "L105", name: "蒙古高原", country: "蒙古", province: "", city: "", lat: 45, lng: 105, historical_name: "", location_description: "", type: "途经", desc: "蒙古地区，斯诺远眺。" },
    { id: "L106", name: "云南高地", country: "中国", province: "云南省", city: "", lat: 25, lng: 102, historical_name: "", location_description: "云南地区重要地点", type: "途经", desc: "云贵高原，斯诺旅行。" },
    { id: "L107", name: "蒙古边地", country: "蒙古/中国北部", province: "", city: "", lat: 45, lng: 110, historical_name: "", location_description: "", type: "途经", desc: "中蒙边境，斯诺提及。" },
    { id: "L108", name: "陕甘宁特区", country: "中国", province: "陕西/甘肃/宁夏", city: "", lat: 36, lng: 108, historical_name: "陕甘宁革命根据地", location_description: "历史地名陕甘宁革命根据地，中国重要地点", type: "重大事件", desc: "陕甘宁革命根据地。" },
    { id: "L109", name: "宝鸡", country: "中国", province: "陕西省", city: "宝鸡", lat: 34.3639, lng: 107.2386, historical_name: "", location_description: "", type: "途经", desc: "陕西西部，工合西北总部所在地。" },
    { id: "L110", name: "陕甘宁边区", country: "中国", province: "陕西/甘肃/宁夏", city: "", lat: 36, lng: 108, historical_name: "陕甘宁革命根据地", location_description: "历史地名陕甘宁革命根据地，中国重要地点", type: "重大事件", desc: "同L108。" },
    { id: "L111", name: "南洋", country: "（东南亚）", province: "", city: "", lat: 5, lng: 110, historical_name: "", location_description: "东南亚地区重要地点", type: "途经", desc: "东南亚地区，斯诺蜜月旅行。" },
    { id: "L112", name: "江西", country: "中国", province: "江西省", city: "", lat: 27, lng: 115, historical_name: "", location_description: "江西地区重要地点", type: "途经", desc: "中央苏区所在地。" },
    { id: "L113", name: "安徽省", country: "中国", province: "安徽省", city: "", lat: 31.8, lng: 117.3, historical_name: "", location_description: "安徽地区重要地点", type: "途经", desc: "华东省份，皖南事变发生地。" },
    { id: "L114", name: "长江", country: "中国", province: "（流经多省）", city: "", lat: 30.5, lng: 114, historical_name: "", location_description: "", type: "途经", desc: "中国第一大河，斯诺多次乘船。" },
    { id: "L115", name: "加利福尼亚", country: "美国", province: "加利福尼亚州", city: "", lat: 36.7783, lng: -119.4179, historical_name: "", location_description: "", type: "其他", desc: "美国西部，斯诺少年时期旅行地。" },
    { id: "L116", name: "亚利桑那州", country: "美国", province: "亚利桑那州", city: "", lat: 33.7298, lng: -111.4312, historical_name: "", location_description: "", type: "其他", desc: "美国西南部，斯诺休养地。" },
    { id: "L117", name: "长春", country: "中国", province: "吉林省", city: "长春市", lat: 43.8171, lng: 125.3235, historical_name: "", location_description: "中国东北地区重要中心城市，曾为满洲国首都。", type: "途经", desc: "伪满洲国首都，斯诺经过。" },
    { id: "L118", name: "苏州", country: "中国", province: "江苏省", city: "苏州市", lat: 31.299, lng: 120.5853, historical_name: "", location_description: "", type: "途经", desc: "江南水乡，斯诺蜜月旅行。" },
    { id: "L119", name: "华盛顿", country: "美国", province: "哥伦比亚特区", city: "华盛顿特区", lat: 38.9072, lng: -77.0369, historical_name: "", location_description: "美利坚合众国首都", type: "其他", desc: "美国首都，斯诺会见罗斯福总统。" },
    { id: "L120", name: "伦敦", country: "英国", province: "", city: "伦敦", lat: 51.5074, lng: -0.1278, historical_name: "", location_description: "英国首都", type: "其他", desc: "英国首都，斯诺与《每日先驱报》合作。" },
    { id: "L121", name: "大连", country: "中国", province: "辽宁省", city: "大连市", lat: 38.914, lng: 121.6147, historical_name: "", location_description: "", type: "途经", desc: "东北港口，南满铁路终点。" }
];

// 可选：过滤出有有效经纬度的地点用于地图展示
const locationsWithCoords = locations.filter(loc => loc.lat !== null && loc.lng !== null);

// 去重（按name去重，保留第一个）
const uniqueLocations = [];
const nameSet = new Set();
for (const loc of locations) {
    if (!nameSet.has(loc.name)) {
        nameSet.add(loc.name);
        uniqueLocations.push(loc);
    }
}

const eventsData = [
    {
        event_id: "E001",
        name: "西安事变",
        categories: ["政治事件"],
        start: "1936-12-12",
        end: "1936-12-25",
        importance: "极高",
        desc: "张学良在西安擒拿蒋介石，旨在劝其停止内战，展开抗战",
        location: "西安",
        event_text: "东北军南撤的同时，红军开进延安，南下至西安城郊，东进至黄河。我想在这里对彻底改变了蒋介石的命运的西安事变的“内幕”作一番新的记述。对张少帅采取这一极端步骤，与红军结盟，成立西北自卫政府的动机，许多人已著书作了解释。但是，他为什么决定取消联盟，在拘禁蒋介石两周之后，又释放了他，并随他回南京接受审讯——而且至今尚被囚禁在台湾！——其原因从未完全披露过。就我来说，我在写西安事变时，对其了解的程度比一般人要多，因为无论在事变前，或事变期间，我同共产党和东北军都有秘密的接触。尽管如此，我了解的也不尽全面。直至不久以前，我才得以提供有关西安事变的新资料，多少改变了历史学家对其作出的解释；但是，对一般读者，我就不必在这里重复那些详情细节了。蒋介石在他的日记中"
    },
    {
        event_id: "E002",
        name: "皖南事变",
        categories: ["军事冲突"],
        start: "1941-01-01",
        end: "1941-01-14",
        importance: "高",
        desc: "国民党命令新四军撤离根据地北移，导致冲突并发生屠杀",
        location: "泾县",
        event_text: "种政策。其他不愿“损害中国事业”的新闻记者也没有报道这方面的消息。直到一九四一年“新四军事件”(皖南事变)发生后，这种在日本战线后方和周围发生的战争中的严重性，终于向外界透露了。   大    屠    杀  新四军的核心力量是一九三四年老红军主力向西北转移时，在江西的几个“袋状地区”幸存下来的一部分共产党员。当日本军队侵占长江下游时，蒋介石命令这些残余部队整编成一支国军，归统一战线指挥。领导新四军的是老共产党员项英将军和非共产党员、黄埔军校出身的叶挺将军。他们的战斗部队大部分驻扎在长江以北的敌后。他们在长江南岸未被占领的地区设有一个根据地总部，并在那里办了几所学校、一座医院和一些小工场。根据地周围都是国民党的军队。 一九四一年一月中旬，新四军突然接到战区"
    },
    {
        event_id: "E003",
        name: "一九二七年的反革命事变",
        categories: ["政治事件"],
        start: "1905-04-10",  // 保留Excel原始错误日期，可注释说明实际为1927年
        end: "1905-04-10",
        importance: "中",
        desc: "",
        location: "",
        event_text: ""
    },
    {
        event_id: "E004",
        name: "西北大饥荒",
        categories: ["自然灾害"],
        start: "1905-04-12",
        end: "1905-04-13",
        importance: "高",
        desc: "在整个西北地区发生的大饥荒",
        location: "萨拉齐",
        event_text: "，我才重返美国。 出国的头一年底，我离开家乡已相当遥远了。我到了戈壁滩南面的火城萨拉齐①。在中国西北那个地方，我目睹了成千上万的儿童死于饥荒，那场饥荒最终夺去了五百多万人的生命。这是我一生中一个觉醒的起点。在很长时期内，我见识过各种战争、贫困、暴力和革命的惨象，这一情景是最令我震惊的一幕。直到十五年以后，我才看到了更惨的情景，那就是纳粹分子不耐烦等人们慢慢饿死，竟然用焚尸炉和毒气室毒杀了六、七百万人。 在上海时，我向《密勒氏评论报》主编、《芝加哥论坛报》记者约翰·本杰明·鲍威尔递交了密苏里大学新闻学院院长沃尔特·威廉斯写的一封介绍信。以后派我去西北的正是鲍威尔。 七年以后，我在那里写出了人类历史上伟大革命之一的基本历程，以及投身这场革命的人们。"
    },
    {
        event_id: "E005",
        name: "中国西北饥荒",
        categories: ["自然灾害"],
        start: "1905-04-12",
        end: "1905-04-13",
        importance: "高",
        desc: "从长城以南到黄河之滨的严重饥荒",
        location: "西北",
        event_text: ""
    },
    {
        event_id: "E006",
        name: "抗日战争",
        categories: ["战争"],
        start: "1937-07-07",
        end: "1945-09-02",
        importance: "极高",
        desc: "抗击日本人的战争",
        location: "华北",
        event_text: "派消极抗战、反共反人民的丑态，并以中日战争为背景，论述了国际之间的关系。斯诺对中国人民的抗日战争充满信心。他说：“在这场战争中，中国正输掉每一个战役，然而中国是处在得胜的一边。” 书的后半部介绍了工业合作社运动的缘起和发展，然后是长篇报道作者在一九三九年重访解放区的见闻，重申了民主、自由的中国必胜的信心。此外，在本卷中我们还选了斯诺有关评蒋介石《中国的命运》和有关中国抗战前景的若干篇文章. 第四卷《大河彼岸》(《the other side of the river》), 一九六二年由美国出版公司出版。书前引用了十七世纪法国哲学家巴斯卡尔的话：“法律正义竟以河为界，多么可笑!……还有什么事情能比这更加可笑呢：一个人居然有权杀死我，"
    },
    {
        event_id: "E007",
        name: "日俄战争",
        categories: ["战争"],
        start: "1904-02-08",
        end: "1905-09-05",
        importance: "中",
        desc: "",
        location: "东北",
        event_text: "。在我们当时的驻华大使认为北洋军阀已没有恢复权力的希望之前很久，这家报纸就主张承认国民党政权。自日俄战争爆发后，汤姆·密勒就是该报驻亚洲的首席记者，他对这份报纸的编辑方针具有重要影响。 密勒创办了《密勒氏评论报》和《中国新闻》,在相当长的时期里，后者是亚洲的最好的美国日报。他还成了远东密苏里新闻学院出身的那一大群美国人和中国人的良师益友。他们人数众多，因此他们的对手时常抱怨“密苏里人垄断新闻”。多少年来，从东京到曼谷，主要通讯社和许多家美国报纸的代表人物以及主要英语报纸和杂志的编辑们都是密苏里人。他们大多数人都和密勒一样持激烈的观点：反殖反帝，支持独立，支持民族平等，支持共和政体，支持实行自决，同时也支持美国。因此，他和我的观点有相同之处决非偶然。 一天晚上，当我就"
    },
    {
        event_id: "E008",
        name: "云南支持蒋介石打广西",
        categories: ["政治事件"],
        start: "1905-04-12",
        end: "1905-04-12",
        importance: "中",
        desc: "云南将领以三民主义为名进军，实则为了打通鸦片贸易通路",
        location: "云南",
        event_text: ""
    },
    {
        event_id: "E009",
        name: "张将军处决53人事件",
        categories: ["政治暴力"],
        start: "",
        end: "",
        importance: "中",
        desc: "张将军在昆明杀害了53个人，包括妇女，采取了后脑开枪的办法",
        location: "昆明",
        event_text: ""
    },
    {
        event_id: "E010",
        name: "一·二八事变",
        categories: ["战争"],
        start: "1932-01-28",
        end: "1932-03-03",
        importance: "高",
        desc: "日本军队在上海发动袭击",
        location: "上海",
        event_text: ""
    },
    {
        event_id: "E011",
        name: "太平天国运动",
        categories: ["历史事件"],
        start: "1850-01-11",
        end: "1864-08-01",
        importance: "中",
        desc: "",
        location: "南京",
        event_text: ""
    },
    {
        event_id: "E012",
        name: "上海之战",
        categories: ["战争"],
        start: "1937-08-13",
        end: "1937-11-26",
        importance: "中",
        desc: "中日战争期间在上海发生的战斗",
        location: "上海",
        event_text: "海周围广大地区“非军事化”。蒋介石再次屈服。然而，日本人并不满足于轻易得来的胜利，旋即挑起了上海之战，它在道义上和政治上产生的影响是谁也预料不到的。 日本舰队司令盐泽说：“中国人只认得武力。”他认为，要打掉中国的“抗日态度”,出动几千名水兵就够了，用不着陆军的帮助。此时，日本陆军由于已在东北得手而目空一切。海军此刻正得到更多的军舰和兵员的补充，可以同西方决一雌雄了。 盐泽把一切都考虑到了，唯独没估量到十九路军的态度。有谁会料想到，在日军的进攻下，甚至在蒋介石和他的政府已从南京逃到洛阳之后，十九路军勇敢而自豪的军官们也没有退却呢? 十九路军是长江下游最出色的军队，一支“新军”,它是国民革命的产物。它的将领曾追随蒋介石反对过共产党，但是，他们有着炽热的爱国心。"
    },
    {
        event_id: "E013",
        name: "沈阳事件",
        categories: ["政治事件"],
        start: "1931-09-18",
        end: "1931-09-18",
        importance: "高",
        desc: "日本关东军炸毁南满铁路路段，以此为口实侵占东北",
        location: "沈阳",
        event_text: "这一事件”却成了日本人进行惩罚性行动的借口。结果日本人侵占了中国最富饶的地区满洲里。但是，“沈阳事件”与其说是开端，倒不如说是先前六次战事及其“意想不到”的结果和“争端”的最终产物。 当日本成为亚洲最先进的工业国时，靠轻易扩张以解决国内的棘手问题的途径已经闭塞。印度、缅甸、印度支那、马来亚和菲律宾依然为白人统治者所控制。除美国之外他们毫无让步的迹象，除非用武力才能把他们除掉。广大的不发达地区如苏门答腊、西利伯斯①和婆罗洲②则荒唐地成了远方小国荷兰①西利伯斯(Celebes), 即苏拉威西岛，印尼中部岛屿。——译注 ② 即加里曼丹——译注         的世袭领地。荷兰显然不是日本的对手。而整个澳大拉西亚① 已被英国人攫夺。东方国家的移民是受排斥的。 到了一九三一"
    },
    {
        event_id: "E014",
        name: "珍珠港事件",
        categories: ["战争"],
        start: "1941-12-07",
        end: "",
        importance: "高",
        desc: "",
        location: "珍珠港",
        event_text: "人的看法。当我与阿奇博尔德 ·克拉克一卡尔爵士交上朋友时，我在这方面开始受到了教育。但是，在珍珠港事件发生前的几年里，英国由于在亚洲一贯实行倒退的政策，它的优点黯然失色了，有远见卓识的英国人很快就认识到了这一点。我小时候从爱尔兰亲戚那里听到了他们对英国帝国主义的指责。看来，他们的言谈一定对我产生了影响，使我相信，凡是英国人在那里当太上皇的地方，道义和上帝总是在叛逆者的一边。 《密勒氏评论报》同样反对当时对中国人的社会歧视，尤其反对在中国人自己的国土上歧视他们。它嘲笑了顽固保守分子的“优等民族”论。它为结束各家俱乐部、公园和外滩花园的排斥中国人的做法，尽了一定的力量。有的办公楼甚至要中国人从另外的门出入。《密勒氏评论报》所在的电报大楼就是如此。 在我担"
    },
    {
        event_id: "E015",
        name: "中法战争",
        categories: ["战争"],
        start: "1883-12-01",
        end: "1885-06-09",
        importance: "中",
        desc: "发生在八十年代的战争",
        location: "越南、中国东南沿海",
        event_text: ""
    },
    {
        event_id: "E016",
        name: "辛亥革命",
        categories: ["政治革命"],
        start: "1911-10-10",
        end: "1912-02-12",
        importance: "高",
        desc: "文中称为第一次革命",
        location: "中国",
        event_text: "夫子的信徒方能从他的讽刺和幽默中觉察出非常危险的东西。 《阿 Q正传》叙述了一个典型无知识的苦力在辛亥革命期间的遭遇，揭示这场革命完全脱离了人民。它和西方文学中捷克的经典作品《好兵帅克》有点相似。但是，帅克至少可以寄身于表面纪律严明实则混乱不堪的军队，尽管他自己也莫名其妙，而阿Q则不明不白地连个安身之处也没有。阿Q时常碰壁，以无         知和迷信来看待世事，浑浑噩噩。他一次又一次地受到侮辱，但总是能用精神胜利法把失败解释成胜利，接着又以高人一等的姿态出现(请参阅孔子、尼采和华尔兑 ·米蒂的著作)。甚至在他因莫须有的罪名而被绑赴法场杀头时，他还说出了半句他自己也不解其意的戏曲中的话，“过了二十年又是一个(好汉)”。 具有共产主义思想的知识分子从鲁迅这篇故事中，看"
    },
    {
        event_id: "E017",
        name: "青年造反",
        categories: ["社会运动"],
        start: "1905-04-18",
        end: "1935-12-01",
        importance: "中",
        desc: "全国性的学生抗议浪潮",
        location: "",
        event_text: ""
    },
    {
        event_id: "E018",
        name: "新生活运动",
        categories: ["社会运动"],
        start: "1905-04-17",
        end: "1905-05-02",
        importance: "中",
        desc: "",
        location: "全国",
        event_text: "颁布的政策要求吸鸦片者必须出示特许证。数百名违禁者被带到北京城外砍头，“以儆效尤”。这是国民党“新生活运动”的一项措施。但事隔不久，数百名“阿Q”光顾了朝鲜人开设的鸦片馆，同样触犯了条例，只因为这些鸦片馆是受到京津警察当局的格外保护，却得到了从轻发落。 后来，日本人决定要结束这场滑稽戏，要把华北割出去，使它与国民党政权完全脱离。他们尚未作好开战的准备，就召来了他们的阴谋专家“沈阳事件”的主谋土肥原。据说，土肥原把一千万元崭新的中国钞票放在桌上，要求宋将军宣布脱离蒋介石的南京政府。 据宋哲元的一位年轻秘书马云汉告诉我，土肥原还拿出了几份文件，证明如果日方坚持，蒋介石已原则上同意撤换宋哲元。 诸如此类事情，外国记者多少有所了解；我们曾设法向国外发了一些"
    },
    {
        event_id: "E019",
        name: "五四运动",
        categories: ["社会运动"],
        start: "1905-04-02",
        end: "1919-06-28",
        importance: "高",
        desc: "由少数学生掀起，最终拯救了中国，迫使日本放弃特权和领土要求",
        location: "北京",
        event_text: "定——自己留在中国。 凡尔赛条约在中国引起了极大的震惊和愤怒，其中马上产生的后果就是一九一九年的五四运动，这个运动的领导人包括学生和知识分子，毛泽东也是其中之一。五四运动对中国的文化有着极其重要的影响——改革了根深蒂固的文言文，摒除了孔子学说的残余势力，此外还引起了重大的政治结果。为了唤醒全国人民的爱国心，团结一致抵抗和打败日本化中国为其殖民地的野心(见诸一九一五年之“二十一条条约”),学生和知识分子显示了惊人的士气和政治力量，并且预告了军阀统治的终结。五四运动还揭露了凡尔赛宫列强的伪善和自私自利的本质，并且使苏联十月革命的反帝和革命的精神得以传入全中国。在这个时刻，孙中山转而向列宁求助，最后终于如愿以偿。 刚从反动阶级手里夺取了政权，布尔什维克便向中国"
    },
    {
        event_id: "E020",
        name: "学生示威",
        categories: ["社会运动"],
        start: "1935-12-09",
        end: "1935-12-01",
        importance: "中",
        desc: "北京学生在街头举行的大规模爱国示威活动，反对伪独立运动",
        location: "北京",
        event_text: "南)盛产大米的地区，革命者在那里占领了好几个地区，并且建立了一个所谓的“共和国”。在大叨的一次学生示威中，法国人开枪打死了好些手无寸铁的百姓。被夸大了的情况传到了几个村子里，学生们举行了没有武装的示威游行。示威群众到了大叨，向傀儡儿皇帝保大递交了要为死难者举行哀悼的请愿书。法国人头脑又一次发昏，出动飞机进行轰炸，用机枪扫射游行队伍，打死了更多的安南人。 现在，他们不得不往越南增调军队。 我通过一个中国商人，见到了一些受过法国教育的安南人。他们帮我搞到了几份叛乱分子向河内提出的实现和解的“条件”。他们的“最高要求”是建立一个立宪政府，一个由民众选举的有立法权的议会，但法国总督对立法拥有否决权。其他“要求”包括废止农奴制(迄今仍是合法的制度),废止一夫多妻制，"
    },
    {
        event_id: "E021",
        name: "九年内战",
        categories: ["内战"],
        start: "1905-04-10",
        end: "1905-04-19",
        importance: "中",
        desc: "中国红区成为未知之地的背景",
        location: "中国",
        event_text: "但是，那时我们俩都不知道红军是什么样子。我们甚至不敢肯定，他们是否是“真正的”共产党人。九年内战使“红色中国”更是成了“未知之地”。我向《纽约太阳报》和《每日先驱报》秘密提议，让我突破对西北共产党控制区周围的封锁，进入红区。两家报纸都赞成我的计划。《每日先驱报》答应负担我此行的全部费用，并且如获成功，还将付我一笔可观的奖金。当时在兰登姆出版社的哈里森·史密斯也向我约稿，并预付了少量稿费。 由于得到了这些支持，我便到上海去，再次去拜访孙逸仙夫人。我请她帮助我，以便红军起码把我作为一个中立者来接待，而不把我当作间谍。一九三六年春，我从上海回到北京，宋庆龄为我作了安排。通过她，我与北京的一位教授取得了联系，他给了我一封致毛泽东的介绍信，还"
    },
    {
        event_id: "E022",
        name: "内战",
        categories: ["内战"],
        start: "1905-04-10",
        end: "1905-05-02",
        importance: "中",
        desc: "美国南北战争",
        location: "美国",
        event_text: "长江而上，发动攻势。尽管各处城镇进行了顽强的抵抗，但都相继失陷了。 美国政府当时虽然忙于本国的内战，从未正式参加干涉，但是议会批准了借用英国正规军官和士兵，批准了大规模的鸦片、武器和船只买卖。许多美国人贪图优厚的报酬，都参加了进去。外国的枪炮远比中国的武器优越，加以有外国人训练和指挥，这就使太平军损失愈加惨重。苏州失陷。戈登将军俘获了太平天国王族的大多数成员。因戈登亲口允诺给予保护，他们方投降。戈登颇不情愿地把他们转交给了李鸿章。李鸿章立刻把他们和他们的数百名追随者一起斩首了。开初，戈登对李鸿章这种操之过急的做法颇为不快，但他们随即言归于好，戈登又继续率领联军乘胜前进。他们彻底击溃了长江下游的太平军，包围了太平军首都南京。这时，李鸿章感到大肆劫掠"
    },
    {
        event_id: "E023",
        name: "二万五千里长征",
        categories: ["军事行动"],
        start: "1934-10-16",
        end: "1935-10-22",
        importance: "极高",
        desc: "红军的战略转移",
        location: "中国",
        event_text: "一切 以及还有更多的东西，都体现在现代史上无与伦比的一次远征的历史中了。 红军说到它时，一般都叫“二万五千里长征”,从福建的最远的地方开始，一直到遥远的陕西西北部道路的尽头为止，其间迂回曲折，进进退退，因此有好些部分的长征战士所走过的路程肯定有那么长，甚至比这更长。根据一军团按逐个阶段编的一张精确的旅程表①,长征的路线共达一万八千零八十八里，折合英 里为六千英里，大约为横贯美洲大陆的距离的两倍，这个数字大约是主力部队的最低行军长度。不要忘记，整个旅程都是步行的，有些是世界上最难通行的小道，大多数无法通行车辆轱辘，还有亚洲最高的山峰和最大的河流。从头到尾都是一场旷日持久的战斗。 有四道主要的防御工程，在钢筋混凝土机枪阵地和碉堡网的支持下，包围着中国西南②的苏"
    },
    {
        event_id: "E025",
        name: "抗战",
        categories: ["战争"],
        start: "1937-07-07",
        end: "1945-09-02",
        importance: "极高",
        desc: "中国抗日战争",
        location: "中国",
        event_text: "了一九三七年芦沟桥事变后日本帝国主义大举侵华的情况。热情地报道了中国共产党坚持进步、坚持抗战的政策，揭露了国民党反动派消极抗战、反共反人民的丑态，并以中日战争为背景，论述了国际之间的关系。斯诺对中国人民的抗日战争充满信心。他说：“在这场战争中，中国正输掉每一个战役，然而中国是处在得胜的一边。” 书的后半部介绍了工业合作社运动的缘起和发展，然后是长篇报道作者在一九三九年重访解放区的见闻，重申了民主、自由的中国必胜的信心。此外，在本卷中我们还选了斯诺有关评蒋介石《中国的命运》和有关中国抗战前景的若干篇文章. 第四卷《大河彼岸》(《the other side of the river》), 一九六二年由美国出版公司出版。书前引"
    },
    {
        event_id: "E026",
        name: "土地改革",
        categories: ["政治运动"],
        start: "1905-04-29",
        end: "1905-05-06",
        importance: "中",
        desc: "发动贫苦农民参加的土地改革",
        location: "中国",
        event_text: "的苏维埃政权被彻底摧毁之前，死亡的人数在二百万至六百万之间。在其它地区，国民党自己早期的“土地改革”的口号(最初是提“平均地权”),先是被抛弃，继而成了“颠覆性”的口号，国民党公然恢复官僚阶级和农村地主豪绅阶级的传统联盟。地主阶级雇用的“民团”,此时由国民党加以武装和训练，用以对抗“赤匪”。 当这种情况在发展的时候，在上海和其它通商口岸“绿洲”中的许多外国人却仍在享福。他们对中国农村混乱解体，正孕育着一场激烈革命的情况一无所知。魏德迈①数年前在美国国会的一个委员会作证时反映了他们目光的短浅。魏德迈在第二次世界大战中接替史迪威将军之前，从未到过中国，但是，他却在美国参议员们的面前，把三十年代的中国描绘成田园生活的乐土。他说“许多在远东住了多年的"
    },
    {
        event_id: "E027",
        name: "红区之行",
        categories: ["人物行迹"],
        start: "1936-06-01",
        end: "1936-10-01",
        importance: "中",
        desc: "埃德加·斯诺访问红军苏区的经历",
        location: "陕北",
        event_text: "市中心，经过鼓楼， 进了一座房子——根据张学良元帅的命令，我被安排住在这里。我的红区之行结束了。但是临了发生了一桩意外之事，差一点儿使我枉此一行。我下车时，发现我的提包不见了—里面装有我所有的访问记录、日记、笔记和第一次在苏区拍摄的照片。事情是这样的，我乘的那辆卡车装着一些麻袋，里面塞满东北军送去修理的破枪支；为了避免受到检查，把我的提包也塞入其中一个麻袋。黑夜里，所有的麻袋被扔在离西安二十英里的一个军火库了。 我费了好多口舌才说服了司机和那位军官立即回去找回那些贵重物品。我一夜不曾合眼，心想万一我那提包被军火库的国民党宪兵发现没收，不知会有什么后果。第二天一大早，我的朋友们踉踉跄跄地进了屋，带回了我的提包，提包原封未动。使我倍感幸运的是，他们回来不久，"
    },
    {
        event_id: "E028",
        name: "中日战争",
        categories: ["战争"],
        start: "1937-07-07",
        end: "1945-09-02",
        importance: "极高",
        desc: "历时八年的战争",
        location: "中国",
        event_text: "了中国共产党的坚持进步、坚持抗战的政策，揭露了国民党反动派消极抗战、反共反人民的丑态，并以中日战争为背景，论述了国际之间的关系。斯诺对中国人民的抗日战争充满信心。他说：“在这场战争中，中国正输掉每一个战役，然而中国是处在得胜的一边。” 书的后半部介绍了工业合作社运动的缘起和发展，然后是长篇报道作者在一九三九年重访解放区的见闻，重申了民主、自由的中国必胜的信心。此外，在本卷中我们还选了斯诺有关评蒋介石《中国的命运》和有关中国抗战前景的若干篇文章. 第四卷《大河彼岸》(《the other side of the river》), 一九六二年由美国出版公司出版。书前引用了十七世纪法国哲学家巴斯卡尔的话：“法律正义竟以河为界，多么可笑"
    },
    {
        event_id: "E029",
        name: "卡尔逊访问延安",
        categories: ["人物行迹"],
        start: "1905-04-20",
        end: "1905-04-21",
        importance: "中",
        desc: "伊万斯·卡尔逊访问延安并会见红军将领",
        location: "延安",
        event_text: ""
    },
    {
        event_id: "E030",
        name: "第一次世界大战",
        categories: ["战争"],
        start: "1914-07-28",
        end: "1918-11-11",
        importance: "中",
        desc: "",
        location: "欧洲",
        event_text: "前才从那里回来的。我象其他人一样，曾以为中国人是决不会打仗的。可现在，就在这条臭气熏天的弄堂里，第一次世界大战以来最大的战斗开始了。 我不知道沪宁铁路的运输经理程宝成(译音)是否已经把旅客和全部车辆撤离遭到公开袭击的北站。我曾去那里想了解究竟出了什么事，却发现一切都照旧。我忙着找负责人，结果找到了那位程先生。我对他说，我刚去过日本舰队司令盐泽的司令部，获悉他正命令日本海军陆战队开进闸北。闸北位于上海中国人管理的那部分地区的中心，在苏州河和公共租界以北的工商业区。 在我们附近的车站里，依然象平时一样拥挤、嘈杂：背着沉重行李铺盖的男男女女，一篓篓新鲜水果和装着鲜鱼的竹筐，堆得高高的坛坛罐罐。嗷嗷待哺的婴儿，端着蟋蟀罐和提着鸟笼的老头。 数以百计天真的旅"
    },
    {
        event_id: "E031",
        name: "工合建立小工厂",
        categories: ["工业运动"],
        start: "1940-10-01",
        end: "1905-04-28",
        importance: "中",
        desc: "在十六省建起了二千三百个小工厂",
        location: "中国",
        event_text: ""
    },
    {
        event_id: "E032",
        name: "反革命时期",
        categories: ["政治时期"],
        start: "1905-04-10",
        end: "1905-04-19",
        importance: "中",
        desc: "",
        location: "中国",
        event_text: "助巩固民主集中制的各方面”以及“社会主义道路和党的领导。” 毛也承认党曾经犯了一些错误。在“镇压反革命时期”,曾出现有“太过份”的现象。他命令对所有刑罚与被剥夺选举权的人重新进行理智的调查，并要求“将错误纠正过来”。他承认计划上的错误造成了供与求之间的“不平衡”,并保证国家的农业税将稳定地维持在目前的水平不变。他警告党员们要“不尚空谈”,对人民不要妄自尊大。他注意到当时发生的一些“乱子”(如农民与干部之间发生的冲突与打斗),并且指出“发生闹事的更重要的因素，是领导上的官僚主义。”其中“十分坏的”是“我们有些干部”出现了“不愿与人民群众同甘共苦，只顾个人地位和得失”。他接着提出警告：“这批人中很多要回到生产岗位上去”。 毛的讲话当然就是要发动群众对"
    },
    {
        event_id: "E033",
        name: "民族民主革命",
        categories: ["政治革命"],
        start: "1905-04-02",
        end: "1905-05-02",
        importance: "中",
        desc: "反帝反封建的任务",
        location: "中国",
        event_text: "命。 他说：“我们始终是社会革命家，我们从来不是改良主义者。中国革命有两大目标。第一个目标是实现民族民主革命的任务(斯诺按：即反帝反封建)。另一个目标是社会主义革命。后者必须实现，而且要彻底实现。目前革命的目标是民族民主性质的但是在一个阶段以后，它将变为社会主义革命。”① 在这一讲话被广泛引用之后，中国记者中很少有人相信“土地改革”的神话了。荒谬的是，国民党政府仍然把这种提法作为它的官方宣传路线，国民党官员继续设法使外交官和记者们相信中国共产主义者“作为一个党已不复存在”,他们已经放弃了马克思主义。阿奇博尔德 ·克拉克-克尔先生告诉我，蒋介石声称共产党员已经"
    },
    {
        event_id: "E034",
        name: "社会主义革命",
        categories: ["政治革命"],
        start: "1905-05-02",
        end: "1905-05-09",  // 保留Excel原始错误日期
        importance: "中",
        desc: "民族民主革命转变而来的革命阶段",
        location: "中国",
        event_text: "者。中国革命有两大目标。第一个目标是实现民族民主革命的任务(斯诺按：即反帝反封建)。另一个目标是社会主义革命。后者必须实现，而且要彻底实现。目前革命的目标是民族民主性质的但是在一个阶段以后，它将变为社会主义革命。”① 在这一讲话被广泛引用之后，中国记者中很少有人相信“土地改革”的神话了。荒谬的是，国民党政府仍然把这种提法作为它的官方宣传路线，国民党官员继续设法使外交官和记者们相信中国共产主义者“作为一个党已不复存在”,他们已经放弃了马克思主义。阿奇博尔德 ·克拉克-克尔先生告诉我，蒋介石声称共产党员已经“投降”,把八路军的领导人说成共产党员是错误的。 蒋介石当"
    },
    {
        event_id: "E035",
        name: "新四军事件",
        categories: ["军事冲突"],
        start: "1941-01-01",
        end: "1941-01-14",
        importance: "中",
        desc: "国民党军队伏击新四军后卫力量，导致项英被杀，叶挺重伤。同E002",
        location: "泾县",
        event_text: "说中国根本就“没有共产党”军队。他还要求我的编辑表示道歉，但遭到了拒绝。 几天以后，英国外交官证实新四军事件是真实的。他们还向伦敦报告，国民党即将对延安大举进攻。这时委员长才勉强作了部分的承认，但他声称是新四军袭击了他的部队。后来，驻重庆的外国记者对当局扣压他们也曾试图发出的报道一事纷纷提出抗议，国民党才不得不暂时把新闻检查放宽一些。过了不久，长期以来一直被掩盖起来的关于统一战线濒于瓦解的全部真相才被抖了出来。 后来我才知道华盛顿对这些电讯极感兴趣，以致于它中断了向中国提供一笔新贷款的谈判。摩根索先生(美国当时的财长——译注)甚至明确表示，如果重开内战，重庆就别指望从美国获得更多的财政援助。 这清楚地表明，美国是否向蒋介石提供战时支援要看他是"
    }
];

// 按开始时间排序（可选，但已有）
eventsData.sort((a, b) => new Date(a.start) - new Date(b.start));


// ==================== 著作/作品数据 ====================
// ==================== 著作数据（基于Excel Work表） ====================
const works = [
    { id: "W001", title: "我在旧中国十三年", alias: "", type: "图书", release_date: "1973/03", description: "美国著名作家、中国人民的朋友埃德加·斯诺所著《旅生于北方之地》/《复始之旅》（Journey To The Beginning）一书的摘译，译文原载香港《文汇报》。" },
    { id: "W002", title: "旅行于方生之地", alias: "复始之旅", type: "图书", release_date: "1958", description: "埃德加·斯诺记者生涯的自述，1958年由美国出版公司出版" },
    { id: "W003", title: "新中国", alias: "", type: "特刊", release_date: "1928", description: "斯诺在上海参加编辑的《密勒氏评论报》（China Weekly Review）的《新中国》特刊。" },
    { id: "W004", title: "旅行文章", alias: "", type: "文章", release_date: "1929", description: "斯诺受中国铁道部委托，对中国铁路系统进行考察后撰写的系列旅行报道。" },
    { id: "W005", title: "《两种时间》", alias: "", type: "图书", release_date: "1950", description: "格雷厄姆·佩克（Graham Peck）的作品，记录了他在20世纪40年代中国的见闻。" },
    { id: "W006", title: "纽约《先驱论坛报》", alias: "", type: "报纸", release_date: "1930", description: "美国著名报纸，斯诺曾担任其驻华特派记者。" },
    { id: "W007", title: "《中午的黑暗》", alias: "", type: "图书", release_date: "1940", description: "阿瑟·库斯勒（Arthur Koestler）的代表作，描写了斯大林肃反运动时期的政治寓言。" },
    { id: "W008", title: "中午的黑暗", alias: "", type: "图书", release_date: "1940", description: "同W007，阿瑟·库斯勒的经典小说。" },
    { id: "W009", title: "现代历史", alias: "", type: "文章/期刊", release_date: "1934", description: "指《现代历史》（Current History）杂志，斯诺曾在此发表多篇关于中国局势的文章。" },
    { id: "W010", title: "《密勒氏评论报》", alias: "", type: "出版物", release_date: "1917/06", description: "又名《中国每周评论》（China Weekly Review），由鲍威尔创办，斯诺在此开始其驻华记者生涯。" },
    { id: "W011", title: "《中国新闻》", alias: "", type: "出版物", release_date: "1920", description: "即《中国新闻》（China News），斯诺曾为其撰稿的报刊。" },
    { id: "W012", title: "《纽约太阳报》", alias: "", type: "报纸", release_date: "1833", description: "《纽约太阳报》（New York Sun），斯诺曾为其供稿。" },
    { id: "W013", title: "《芝加哥每日新闻》", alias: "", type: "报纸", release_date: "1875", description: "《芝加哥每日新闻》（Chicago Daily News），斯诺担任其驻华记者。" },
    { id: "W014", title: "《今日世界》", alias: "", type: "出版物", release_date: "1900", description: "《今日世界》（World Today），斯诺曾为其撰写文章。" },
    { id: "W015", title: "《中国真理》", alias: "", type: "出版物", release_date: "1920", description: "《中国真理》（The China Truth），在广州出版的英文周刊，斯诺曾为其供稿。" },
    { id: "W016", title: "马可孛罗的游记", alias: "", type: "图书", release_date: "1298", description: "马可·波罗在狱中口述，由鲁斯蒂谦记录的游记。" },
    { id: "W017", title: "《活跃的中国》", alias: "", type: "书籍", release_date: "1936", description: "斯诺编译的现代中国短篇小说集，旨在向西方介绍中国现代文学。" },
    { id: "W018", title: "《美月信使》", alias: "", type: "月刊", release_date: "1921", description: "《美月信使》可能是《密苏里校友》（Missouri Alumnus）或相关刊物的译名。" },
    { id: "W019", title: "《远东前线》", alias: "", type: "书籍", release_date: "1933/11", description: "记述上海和东北不宣而战情况的书籍" },
    { id: "W020", title: "凯洛格-布赖恩德公约", alias: "", type: "文件", release_date: "1928/08/27", description: "《非战公约》，又称《凯洛格-布赖恩德公约》，旨在废除战争作为国家政策。" },
    { id: "W021", title: "《西方国家威信的衰落》", alias: "", type: "文章", release_date: "1933/08/26", description: "斯诺发表在《星期六晚邮报》上的文章，分析了西方列强在东方威信的丧失。" },
    { id: "W022", title: "《龙眼所见》", alias: "", type: "自传/叙事诗", release_date: "", description: "" },
    { id: "W023", title: "《康熙字典》", alias: "", type: "字典", release_date: "1716", description: "清朝康熙年间编纂的工具书，是中国古代字典的集大成者。" },
    { id: "W024", title: "《阿Q正传》", alias: "", type: "小说", release_date: "1921/12/04", description: "鲁迅的代表作，描写了阿Q这一典型形象，深刻揭示了国民性。" },
    { id: "W025", title: "《好兵帅克》", alias: "", type: "文学作品", release_date: "1921", description: "捷克作家雅罗斯拉夫·哈谢克的讽刺小说。" },
    { id: "W026", title: "《战争与和平》", alias: "", type: "文学作品", release_date: "1869", description: "列夫·托尔斯泰的史诗巨著。" },
    { id: "W027", title: "请愿书", alias: "", type: "", release_date: "", description: "向蒋介石提出的要求结社自由和言论自由的请愿书" },
    { id: "W028", title: "宣言", alias: "", type: "", release_date: "", description: "张拟发表的关于学生主张的宣言" },
    { id: "W029", title: "《每日先驱报》", alias: "", type: "报纸", release_date: "1911", description: "伦敦《每日先驱报》，斯诺曾担任其驻华特派员。" },
    { id: "W030", title: "《禽鸟世界》", alias: "", type: "杂志", release_date: "", description: "" },
    { id: "W031", title: "《远东将要发生的冲突》", alias: "", type: "文章", release_date: "1936/06", description: "" },
    { id: "W032", title: "《星期六晚邮报》", alias: "", type: "报纸", release_date: "1821", description: "《星期六晚邮报》，美国影响广泛的杂志，斯诺长期为其撰稿。前身1728年由塞缪尔·凯默创办的《宾夕法尼亚公报》" },
    { id: "W033", title: "简传", alias: "", type: "", release_date: "", description: "关于周恩来和邓颖超的简传" },
    { id: "W034", title: "红星照耀着中国", alias: "西行漫记", type: "图书", release_date: "1937/10/21", description: "记录了作者斯诺访问苏区及与毛泽东谈话的内容" },
    { id: "W035", title: "关于红军长征的诗", alias: "", type: "诗歌", release_date: "1935/10", description: "指毛泽东所作的《七律·长征》，由斯诺首次翻译并向外界公布。" },
    { id: "W036", title: "蒋介石日记", alias: "", type: "日记", release_date: "1937", description: "指1937年西安事变后出版的《蒋委员长西安半月记》及附录的日记摘要。" },
    { id: "W037", title: "亚洲之战", alias: "", type: "图书", release_date: "1941", description: "斯诺关于中国抗日战争和亚洲局势的又一重要著作。" },
    { id: "W038", title: "计划书", alias: "", type: "方案", release_date: "", description: "由路易和叙述者起草的关于建立工业合作社的计划。" },
    { id: "W040", title: "芝加哥论坛报", alias: "", type: "报纸", release_date: "1847/06/10", description: "美国中西部地区最具影响力的日报之一。" },
    { id: "W041", title: "《亚洲杂志》", alias: "", type: "杂志", release_date: "1898/01", description: "美国一份专注于东方文化、地理和政治的深度期刊。" },
    { id: "W042", title: "《每日电讯报》", alias: "", type: "报纸", release_date: "1855/06/29", description: "英国全国性大报。" },
    { id: "W043", title: "时代报", alias: "", type: "报纸", release_date: "1785", description: "英国《泰晤士报》(The Times)" },
    { id: "W044", title: "生活杂志", alias: "", type: "杂志", release_date: "1936", description: "美国著名摄影纪实杂志。1937 年，《生活》杂志刊登了斯诺拍摄的毛泽东头戴红星八角帽的著名照片及相关采访摘要" }
];

// ==================== 组织/机构数据 ====================
// ==================== 组织/机构数据（基于Excel Organization表） ====================
const organizations = [
    { id: "O001", name: "密苏里大学新闻学院", type: "教育机构", description: "世界上第一所新闻学院，位于美国密苏里大学。", location: "L019", alias: "" },
    { id: "O002", name: "生活·读书·新知三联书店", type: "出版社", description: "总部位于北京的书店兼出版社，由三家书店合并而成。", location: "L002", alias: "" },
    { id: "O003", name: "中国旅行社", type: "旅行社", description: "1923年由陈光甫创办，是中国人开办的第一家旅行社。", location: "L001", alias: "" },
    { id: "O004", name: "交通部", type: "政府部门", description: "负责交通运输行政管理的政府部门。", location: "L007", alias: "" },
    { id: "O005", name: "南京中央政府", type: "政府", description: "1927年至1948年间中华民国的中央政府。", location: "L007", alias: "" },
    { id: "O006", name: "南满铁路", type: "铁路公司", description: "日本在华进行经济掠夺和政治渗透的机构。", location: "L121", alias: "" },
    { id: "O007", name: "中国工业合作社", type: "社会团体", description: "旨在通过工业合作支援抗战的民间组织。", location: "L001", alias: "工合" },
    { id: "O008", name: "国民党", type: "政党", description: "正式名称为中国国民党，当时的中国统治政党。", location: "L007", alias: "" },
    { id: "O009", name: "苏联政府", type: "政府", description: "苏维埃社会主义共和国联盟的最高行政机关。", location: "L022", alias: "" },
    { id: "O010", name: "美国海军陆战队第四团", type: "军队", description: "曾驻扎于上海的美国海军陆战队精锐部队。", location: "L001", alias: "" },
    { id: "O011", name: "美联社", type: "通讯社", description: "美国最大的通讯社，全球领先的新闻报道机构。", location: "L005", alias: "" },
    { id: "O012", name: "路透社", type: "通讯社", description: "英国跨国新闻通讯社，世界上最早的通讯社之一。", location: "L120", alias: "" },
    { id: "O013", name: "公共租界警方政治部", type: "警察部门", description: "上海公共租界工部局警察局的政治侦察机构。", location: "L001", alias: "" },
    { id: "O014", name: "龙华中国警备队", type: "军队", description: "驻守在上海龙华地区的中国军队警备力量。", location: "L001", alias: "" },
    { id: "O015", name: "统一新闻协会", type: "新闻机构", description: "为多家报纸提供消息的国外新闻机构。", location: "L005", alias: "" },
    { id: "O016", name: "共产党", type: "政党", description: "此处指中国共产党，在农村地区实施民主实验并最终夺取政权的政党。", location: "L003", alias: "" },
    { id: "O017", name: "南京政府", type: "政府", description: "1927年至1948年间驻于南京的中华民国政府。", location: "L007", alias: "" },
    { id: "O018", name: "广州律师协会", type: "社会团体", description: "广州地区的律师行业自律组织。", location: "L035", alias: "" },
    { id: "O019", name: "中国食盐专利公司", type: "公司", description: "当时经营食盐专利业务的相关企业。", location: "L001", alias: "" },
    { id: "O020", name: "美国驻昆明领事馆", type: "外交机构", description: "美国设立在昆明的外交代表机构。", location: "L042", alias: "" },
    { id: "O021", name: "国家银行", type: "金融机构", description: "由政府设立并控制的银行，行使中央银行或主要金融职能。", location: "L007", alias: "" },
    { id: "O022", name: "食盐专利公司", type: "公司", description: "", location: "", alias: "" },
    { id: "O023", name: "韦斯利扬大学", type: "教育机构", description: "", location: "L116", alias: "" },
    { id: "O024", name: "中央研究院", type: "研究机构", description: "", location: "", alias: "" },
    { id: "O025", name: "人权保障同盟", type: "社会组织", description: "", location: "L001", alias: "" },
    { id: "O026", name: "龙华国民党警备队", type: "军事/警备机构", description: "", location: "", alias: "" },
    { id: "O027", name: "日本海军陆战队", type: "军事机构", description: "", location: "", alias: "" },
    { id: "O028", name: "十九路军", type: "军事机构", description: "", location: "", alias: "" },
    { id: "O029", name: "国联", type: "国际组织", description: "", location: "", alias: "" },
    { id: "O030", name: "日本军队", type: "军队", description: "第二次世界大战期间的日本武装力量。", location: "L020", alias: "" },
    { id: "O031", name: "纳粹党", type: "政党", description: "德国国家社会主义工人党。", location: "L047", alias: "" },
    { id: "O032", name: "满洲国", type: "傀儡政权", description: "日本侵占中国东北后扶植的傀儡政权。", location: "L117", alias: "" },
    { id: "O033", name: "燕京大学", type: "教育机构", description: "20世纪初在北京创办的一所著名教会大学。", location: "L002", alias: "" },
    { id: "O034", name: "清华大学", type: "教育机构", description: "位于北京的一所中国顶尖高等学府。", location: "L002", alias: "" },
    { id: "O035", name: "东吴大学", type: "教育机构", description: "创办于苏州的著名教会大学。", location: "L118", alias: "" },
    { id: "O036", name: "中国共产党", type: "政党", description: "在农村地区实施民主实验并最终夺取政权的政党。", location: "L003", alias: "" },
    { id: "O037", name: "蓝衣社", type: "政治组织", description: "三民主义力行社的别称，是国民党内的秘密特务组织。", location: "L007", alias: "" },
    { id: "O038", name: "盖世太保", type: "秘密警察", description: "纳粹德国时期的国家秘密警察。", location: "L047", alias: "" },
    { id: "O039", name: "中国国际饥荒救济委员会", type: "国际组织", description: "负责协调中国饥荒救济的国际机构。", location: "L002", alias: "" },
    { id: "O040", name: "河北-察哈尔自治委员会", type: "行政管理机构", description: "", location: "", alias: "" },
    { id: "O041", name: "美国国会", type: "立法机构", description: "美国最高立法机构，由参议院和众议院组成。", location: "L119", alias: "" },
    { id: "O042", name: "东北大学", type: "教育机构", description: "由张作霖创办于沈阳的著名大学。", location: "L009", alias: "" },
    { id: "O043", name: "古根海姆学会", type: "学术机构", description: "美国著名的学术和艺术研究资助机构。", location: "L005", alias: "" },
    { id: "O044", name: "奥德哈姆出版公司", type: "出版机构", description: "", location: "", alias: "" },
    { id: "O045", name: "英国工党", type: "政党", description: "英国的主要政党之一，代表工人阶级利益。", location: "L120", alias: "" },
    { id: "O046", name: "美国驻北京公使馆", type: "外交机构", description: "美国设在北平（北京）的公使级外交机构。", location: "L002", alias: "" },
    { id: "O047", name: "中国红军", type: "军队", description: "中国共产党领导的革命武装力量，后改为八路军、新四军。", location: "L003", alias: "" },
    { id: "O048", name: "红军", type: "军队", description: "中国共产党领导的革命武装力量，后改为八路军。", location: "L003", alias: "" },
    { id: "O049", name: "东北军", type: "军队", description: "由张作霖、张学良父子领导的奉系军队。", location: "L009", alias: "" },
    { id: "O050", name: "伦敦每日先驱报", type: "报纸", description: "英国的一家日报，曾与英国工党有密切关系。", location: "L120", alias: "" },
    { id: "O051", name: "纽约兰多姆出版社", type: "出版社", description: "", location: "", alias: "" },
    { id: "O052", name: "东线红军", type: "军队", description: "", location: "", alias: "" },
    { id: "O053", name: "黄埔军校", type: "教育机构", description: "中国国民党陆军军官学校，孙中山在中国共产党和社会主义苏联的帮助下创办，是培养军队干部的军事学校。", location: "", alias: "" },
    { id: "O054", name: "中华人民共和国", type: "国家", description: "", location: "", alias: "" },
    { id: "O055", name: "农民游击队", type: "军队", description: "", location: "", alias: "" },
    { id: "O056", name: "外交部", type: "政府部门", description: "", location: "L076", alias: "" },
    { id: "O057", name: "红军学校", type: "教育机构", description: "设于一列窑洞内，收了大约八百名学生", location: "L076", alias: "" },
    { id: "O058", name: "共产主义青年团", type: "青年组织", description: "", location: "", alias: "" },
    { id: "O059", name: "妇女组织", type: "社会组织", description: "", location: "", alias: "" },
    { id: "O060", name: "公安部队", type: "安全部队", description: "", location: "", alias: "" },
    { id: "O061", name: "红军大学", type: "教育机构", description: "", location: "", alias: "" },
    { id: "O062", name: "贫农团", type: "社会团体", description: "", location: "", alias: "" },
    { id: "O063", name: "白军", type: "军队", description: "", location: "", alias: "" },
    { id: "O064", name: "救国会", type: "社会团体", description: "", location: "", alias: "" },
    { id: "O065", name: "中共中央", type: "组织机构", description: "", location: "", alias: "" },
    { id: "O066", name: "日本军国主义者", type: "政治军事团体", description: "", location: "", alias: "" },
    { id: "O067", name: "游击队", type: "武装力量", description: "", location: "", alias: "" },
    { id: "O068", name: "中国共产党妇女部", type: "组织机构", description: "", location: "", alias: "" },
    { id: "O069", name: "北美报业联盟", type: "报业联盟", description: "", location: "", alias: "" },
    { id: "O070", name: "南京傀儡政权", type: "政权", description: "由汪精卫首领的亲日政权", location: "", alias: "" },
    { id: "O071", name: "美国海军陆战队", type: "军事组织", description: "", location: "", alias: "" },
    { id: "O072", name: "八路军", type: "军队", description: "中国共产党领导的抗日武装力量。", location: "L003", alias: "" },
    { id: "O073", name: "英国大使馆", type: "外交机构", description: "", location: "", alias: "" },
    { id: "O074", name: "国民党政府", type: "政府", description: "", location: "", alias: "" },
    { id: "O075", name: "上海市政当局", type: "政府机构", description: "", location: "", alias: "" },
    { id: "O076", name: "保卫中华同盟", type: "社会团体", description: "", location: "", alias: "" },
    { id: "O077", name: "基督教青年会", type: "社会团体", description: "", location: "", alias: "" },
    { id: "O078", name: "密苏里大学", type: "教育机构", description: "", location: "", alias: "" },
    { id: "O079", name: "促进中国工合国际委员会", type: "社会团体", description: "", location: "L038", alias: "" },
    { id: "O080", name: "先驱报", type: "报社", description: "", location: "", alias: "" },
    { id: "O081", name: "CC派", type: "政治派系", description: "", location: "", alias: "" },
    { id: "O082", name: "黄埔派", type: "政治派系", description: "", location: "", alias: "" },
    { id: "O083", name: "宫廷派", type: "政治派系", description: "", location: "", alias: "" },
    { id: "O084", name: "中国银行", type: "金融机构", description: "", location: "", alias: "" },
    { id: "O085", name: "大陆银行", type: "金融机构", description: "", location: "L024", alias: "宋家王朝" },
    { id: "O086", name: "斯旺-卡伯森-弗里茨经纪公司", type: "公司", description: "美国经纪公司", location: "", alias: "" },
    { id: "O087", name: "通用动力公司", type: "公司", description: "美国武器生产公司", location: "", alias: "" },
    { id: "O088", name: "国际委员会", type: "国际组织", description: "", location: "", alias: "" },
    { id: "O089", name: "骆驼运输合作社", type: "合作社", description: "", location: "", alias: "" },
    { id: "O090", name: "合作社管制局", type: "政府机构", description: "", location: "", alias: "" },
    { id: "O091", name: "国家资源委员会", type: "政府机构", description: "主持大规模购买日本货品的机构", location: "", alias: "" },
    { id: "O092", name: "中国农民银行", type: "金融机构", description: "由陈果夫和陈立夫控制的银行", location: "", alias: "" },
    { id: "O093", name: "重庆政府", type: "政府", description: "国民党在战时的政府", location: "", alias: "" },
    { id: "O094", name: "国民党驻华盛顿大使馆", type: "外交机构", description: "", location: "L119", alias: "" },
    { id: "O095", name: "参议院国内安全委员会", type: "立法委员会", description: "", location: "L019", alias: "" },
    { id: "O096", name: "美国国务院", type: "政府机构", description: "", location: "L019", alias: "" },
    { id: "O097", name: "陕甘宁边区政府", type: "政府", description: "", location: "L110", alias: "" },
    { id: "O098", name: "国际工合中心", type: "社会组织", description: "", location: "L110", alias: "" },
    { id: "O099", name: "新四军", type: "军队", description: "南方红军游击队改编的抗日武装力量。", location: "", alias: "" },
    { id: "O100", name: "美国工合委员会", type: "社会组织", description: "", location: "L019", alias: "" },
    { id: "O101", name: "英国工合委员会", type: "社会组织", description: "", location: "L074", alias: "" },
    { id: "O102", name: "荷兰航空公司", type: "航空公司", description: "", location: "", alias: "" },
    { id: "O103", name: "《密勒氏评论报》", type: "报社", description: "由鲍威尔创办，斯诺在此开始其驻华记者生涯。", location: "L001", alias: "" },
    { id: "O104", name: "芝加哥论坛报", type: "报社", description: "", location: "", alias: "" }
];


// 完整人物数据（约140位）
// ==================== 完整人物数据（基于 Excel） ====================
const persons = [
    { person_id: "P001", name: "埃德加·斯诺", nationality: "美国", birth_date: "1905-07-19", death_date: "1972-02-15", occupation: "记者", biography: "毛泽东主席的传记作家", person_alias: "斯诺同志", person_description: "首位深入红区的美国记者，著《红星照耀中国》", type: "center", colorGroup: "center" },
    { person_id: "P002", name: "约翰·本杰明·鲍威尔", nationality: "美国", birth_date: "1888", death_date: "1947", occupation: "记者", biography: "", person_alias: "", person_description: "《密勒氏评论报》主编，在华记者", type: "other", colorGroup: "other" },
    { person_id: "P003", name: "沃尔特·威廉斯", nationality: "", birth_date: "", death_date: "", occupation: "密苏里大学新闻学院院长", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P004", name: "孙科", nationality: "中国", birth_date: "1891-10-20", death_date: "1973-09-13", occupation: "交通部长", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P005", name: "孙夫人", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P006", name: "毛泽东", nationality: "中国", birth_date: "1893-12-26", death_date: "1976-09-09", occupation: "主席", biography: "中国共产党领导人，在保安期间指导革命工作，预见抗日战争走势。", person_alias: "", person_description: "中共领袖，保安接受斯诺专访，指导革命", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P007", name: "周恩来", nationality: "中国", birth_date: "1898-03-05", death_date: "1976-01-08", occupation: "东线红军指挥人, 中华人民共和国总理", biography: "", person_alias: "", person_description: "东线红军指挥，西安事变谈判关键人物", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P008", name: "路易·艾黎", nationality: "美国", birth_date: "1897-12-02", death_date: "1987-12-27", occupation: "首席技术顾问", biography: "在汉口开展工作，致力于建立'工合'。", person_alias: "艾黎", person_description: "工合运动创始人，旅华六十年", type: "foreign_friend", colorGroup: "foreign_friend" },
    { person_id: "P009", name: "蒋介石", nationality: "中国", birth_date: "1887-10-31", death_date: "1975-04-05", occupation: "国民政府领导人", biography: "", person_alias: "", person_description: "国民政府领袖，1927年清党反共", type: "opponent", colorGroup: "opponent" },
    { person_id: "P010", name: "叙述者", nationality: "美国", birth_date: "", death_date: "", occupation: "工业家（原新闻记者）", biography: "", person_alias: "", person_description: "本书作者，美国记者转型工业推动者", type: "other", colorGroup: "other" },
    { person_id: "P011", name: "马可·波罗", nationality: "意大利", birth_date: "1254", death_date: "1324", occupation: "旅行家", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P012", name: "忽必烈", nationality: "蒙古", birth_date: "1215", death_date: "1294", occupation: "蒙古骑兵队统帅", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P013", name: "张学良", nationality: "中国", birth_date: "1901-06-03", death_date: "2001-10-14", occupation: "东北军司令官", biography: "", person_alias: "张少帅", person_description: "发动西安事变，促成国共联合抗日", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P014", name: "C·T·华盛顿·吴", nationality: "", birth_date: "", death_date: "", occupation: "技术专家", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P015", name: "阎锡山", nationality: "中国", birth_date: "1883-10-08", death_date: "1960-05-23", occupation: "绥靖主任", biography: "", person_alias: "", person_description: "山西军阀，长期割据华北", type: "opponent", colorGroup: "opponent" },
    { person_id: "P016", name: "冯玉祥", nationality: "中国", birth_date: "1882-11-06", death_date: "1948-09-01", occupation: "", biography: "", person_alias: "", person_description: "\"基督将军\"，西北军阀领袖", type: "other", colorGroup: "other" },
    { person_id: "P017", name: "格雷厄姆·佩克", nationality: "美国", birth_date: "1914", death_date: "1968", occupation: "", biography: "", person_alias: "", person_description: "美国作家，著《两种时间》记录民国", type: "other", colorGroup: "other" },
    { person_id: "P018", name: "凯斯特勒", nationality: "匈牙利-英国", birth_date: "1905-09-05", death_date: "1983-03-03", occupation: "", biography: "", person_alias: "", person_description: "著《中午的黑暗》揭示极权审讯", type: "other", colorGroup: "other" },
    { person_id: "P019", name: "伊凡诺夫", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P020", name: "伊万斯·福代斯·卡尔逊", nationality: "美国", birth_date: "1896-02-26", death_date: "1947-05-27", occupation: "情报官员", biography: "", person_alias: "", person_description: "美海军陆战队官员，曾访延安", type: "foreign_friend", colorGroup: "foreign_friend" },
    { person_id: "P021", name: "帕特·吉文斯", nationality: "爱尔兰", birth_date: "", death_date: "", occupation: "警方政治部头目", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P022", name: "约翰·根室", nationality: "美国", birth_date: "1901-08-30", death_date: "1970-05-29", occupation: "内幕作家", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P023", name: "托姆·穆尼", nationality: "美国", birth_date: "1882-12-08", death_date: "1942-03-06", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P024", name: "托姆·密勒", nationality: "", birth_date: "", death_date: "", occupation: "首席记者/编辑", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P025", name: "莫里斯·哈里斯", nationality: "", birth_date: "", death_date: "", occupation: "美联社工作人员", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P026", name: "弗兰克·奥利弗", nationality: "", birth_date: "", death_date: "", occupation: "路透社记者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P027", name: "叶剑英", nationality: "中国", birth_date: "1897-04-28", death_date: "1986-10-22", occupation: "", biography: "", person_alias: "", person_description: "中共参谋长，数次于危局中护党", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P028", name: "鲍威尔", nationality: "", birth_date: "", death_date: "", occupation: "记者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P029", name: "密勒", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P030", name: "德鲁·皮尔逊", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P031", name: "戴维·劳伦斯", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P032", name: "爱德华·亨特", nationality: "", birth_date: "", death_date: "", occupation: "统一新闻协会驻北京代表", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P033", name: "孙中山", nationality: "中国", birth_date: "1866-11-12", death_date: "1925-03-12", occupation: "", biography: "", person_alias: "", person_description: "中国革命先行者，三民主义倡导者", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P034", name: "甘德源", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P035", name: "王正廷", nationality: "", birth_date: "1882-09-07", death_date: "1961-05-21", occupation: "外交部长", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P036", name: "G·爱德华·莱昂", nationality: "", birth_date: "", death_date: "", occupation: "律师", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P037", name: "哈里·史蒂文斯", nationality: "美国", birth_date: "", death_date: "", occupation: "美国驻昆明领事", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P038", name: "郭炳干", nationality: "中国", birth_date: "", death_date: "", occupation: "中国食盐专利公司监督官", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P039", name: "姆尔·奥尔德里奇", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P040", name: "张将军", nationality: "", birth_date: "", death_date: "", occupation: "军阀/政权领导者", biography: "", person_alias: "十个老婆的麻子', '三十六匹马张", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P041", name: "约瑟夫·F·罗克", nationality: "美国", birth_date: "", death_date: "", occupation: "博物学家", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P042", name: "史蒂文斯", nationality: "美国", birth_date: "", death_date: "", occupation: "美国驻昆明领事", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P043", name: "宋庆龄", nationality: "中国", birth_date: "1893-01-27", death_date: "1981-05-29", occupation: "保卫中华同盟领导人", biography: "孙中山夫人，致力于中国革命，反对蒋介石独裁，关注人民利益。", person_alias: "孙夫人", person_description: "孙中山夫人，保卫中华同盟领导人", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P044", name: "威廉·布朗·梅洛尼", nationality: "", birth_date: "", death_date: "", occupation: "编辑", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P045", name: "吉米·希恩", nationality: "美国", birth_date: "", death_date: "", occupation: "记者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P046", name: "宋美龄", nationality: "中国", birth_date: "1897-03-04", death_date: "2003-10-23", occupation: "国民党高层", biography: "蒋介石之妻", person_alias: "", person_description: "蒋介石之妻，宋家王朝核心成员", type: "opponent", colorGroup: "opponent" },
    { person_id: "P047", name: "邓演达", nationality: "中国", birth_date: "1895-03-01", death_date: "1931-11-29", occupation: "", biography: "", person_alias: "", person_description: "国民党左派，被蒋介石处决", type: "other", colorGroup: "other" },
    { person_id: "P048", name: "杨铨", nationality: "中国", birth_date: "", death_date: "", occupation: "科学家", biography: "", person_alias: "杏佛", person_description: "科学家，人权活动家，遭暗杀", type: "other", colorGroup: "other" },
    { person_id: "P049", name: "蔡元培", nationality: "中国", birth_date: "1868-01-11", death_date: "1940-03-05", occupation: "", biography: "", person_alias: "", person_description: "教育家，北大校长，推进新文化", type: "other", colorGroup: "other" },
    { person_id: "P050", name: "冯铿", nationality: "中国", birth_date: "", death_date: "", occupation: "小说家", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P051", name: "程宝辰", nationality: "", birth_date: "", death_date: "", occupation: "铁路工作人员", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P052", name: "盐泽", nationality: "日本", birth_date: "", death_date: "", occupation: "日本舰队司令", biography: "", person_alias: "", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P053", name: "吴铁城", nationality: "", birth_date: "", death_date: "", occupation: "上海市长", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P054", name: "程先生", nationality: "", birth_date: "", death_date: "", occupation: "上海北站工作人员", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P055", name: "罗伯特·沃德", nationality: "美国", birth_date: "", death_date: "", occupation: "美国驻上海领事", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P056", name: "帕斯克尔", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P057", name: "霍勒斯·埃普斯", nationality: "", birth_date: "", death_date: "", occupation: "统一新闻协会上司", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P058", name: "尼姆·威尔斯", nationality: "", birth_date: "", death_date: "", occupation: "工业家", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P059", name: "墨索里尼", nationality: "意大利", birth_date: "1883-07-29", death_date: "1945-04-28", occupation: "报纸编辑/政治领导人", biography: "", person_alias: "", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P060", name: "本·罗伯逊", nationality: "", birth_date: "", death_date: "", occupation: "记者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P061", name: "艾尔·史密斯", nationality: "美国", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P062", name: "富兰克林·罗斯福", nationality: "美国", birth_date: "1882-01-30", death_date: "1945-04-12", occupation: "美国总统", biography: "", person_alias: "", person_description: "", type: "foreign_friend", colorGroup: "foreign_friend" },
    { person_id: "P063", name: "吉姆·米尔斯", nationality: "", birth_date: "", death_date: "", occupation: "美联社特派员", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P064", name: "斯彭格勒", nationality: "", birth_date: "", death_date: "", occupation: "作家/哲学家", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P065", name: "尼姆", nationality: "", birth_date: "", death_date: "", occupation: "作家/研究者", biography: "叙述者的妻子", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P066", name: "乔治·霍勒斯·洛里默", nationality: "", birth_date: "", death_date: "", occupation: "《星期六晚邮报》负责人", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P067", name: "L·C·阿林顿", nationality: "", birth_date: "", death_date: "", occupation: "汉学家, 前中国海军军官, 前中国海关官员", biography: "在中国住了五十年，精通中国戏剧和北京历史", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P068", name: "古坦伯格", nationality: "", birth_date: "", death_date: "", occupation: "活版印刷发明者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P069", name: "庄占美", nationality: "", birth_date: "", death_date: "", occupation: "中国银行家", biography: "基督教徒，燕京大学出身", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P070", name: "鲁迅", nationality: "中国", birth_date: "1881-09-25", death_date: "1936-10-19", occupation: "作家, 学问家", biography: "受人尊敬的学问家和伟大作家，患有肺结核病，著作曾被国民党政府查禁。", person_alias: "", person_description: "伟大作家，作品遭国民党查禁", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P071", name: "姚", nationality: "", birth_date: "", death_date: "", occupation: "翻译", biography: "东吴大学毕业生，精通英语，熟悉中国古典文学和现代文学，从事翻译工作。", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P072", name: "阿Q", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "鲁迅作品中的虚构人物，通过其经历显示辛亥革命未扩展到人民当中。", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P073", name: "约翰·戴伊", nationality: "", birth_date: "", death_date: "", occupation: "出版者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P074", name: "冯·塞克特", nationality: "德国", birth_date: "", death_date: "", occupation: "将军", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P075", name: "魏德迈", nationality: "美国", birth_date: "", death_date: "", occupation: "将军", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P076", name: "史迪威", nationality: "美国", birth_date: "", death_date: "", occupation: "将军", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P077", name: "约翰·厄尔·贝克", nationality: "美国", birth_date: "", death_date: "", occupation: "特派调查员", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P078", name: "何应钦", nationality: "中国", birth_date: "1890-04-02", death_date: "1987-10-21", occupation: "参谋长", biography: "", person_alias: "", person_description: "国民党参谋长，主张对日妥协", type: "opponent", colorGroup: "opponent" },
    { person_id: "P079", name: "宋哲元", nationality: "中国", birth_date: "1885-10-30", death_date: "1940-04-05", occupation: "将领", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P080", name: "土肥原", nationality: "日本", birth_date: "", death_date: "", occupation: "阴谋专家", biography: "", person_alias: "", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P081", name: "马", nationality: "", birth_date: "", death_date: "", occupation: "秘书", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P082", name: "张", nationality: "", birth_date: "", death_date: "", occupation: "贫农", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P083", name: "埃德加", nationality: "美国", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P084", name: "王", nationality: "", birth_date: "", death_date: "", occupation: "燕京大学学生/翻译", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P085", name: "陈", nationality: "", birth_date: "", death_date: "", occupation: "学生", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P086", name: "弗兰克·斯马瑟斯", nationality: "", birth_date: "", death_date: "", occupation: "记者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P087", name: "吉米·怀特", nationality: "", birth_date: "", death_date: "", occupation: "记者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P088", name: "麦克·费希尔", nationality: "", birth_date: "", death_date: "", occupation: "记者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P089", name: "C·M·麦克唐纳", nationality: "", birth_date: "", death_date: "", occupation: "记者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P090", name: "蒋介石的侄子", nationality: "", birth_date: "", death_date: "", occupation: "政治宪兵指挥者", biography: "", person_alias: "", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P091", name: "司徒雷登", nationality: "美国", birth_date: "1876-06-24", death_date: "1962-09-19", occupation: "", biography: "", person_alias: "", person_description: "美国驻华大使，燕京大学创办者", type: "foreign_friend", colorGroup: "foreign_friend" },
    { person_id: "P092", name: "纳尔逊·特拉斯勒·詹森", nationality: "美国", birth_date: "1887", death_date: "1954", occupation: "美国大使", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P093", name: "约瑟夫·史迪威", nationality: "美国", birth_date: "1883-03-19", death_date: "1946-10-12", occupation: "武官, 上校", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P094", name: "哈里森·史密斯", nationality: "美国", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P095", name: "王牧师", nationality: "", birth_date: "", death_date: "", occupation: "牧师", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P096", name: "斯诺", nationality: "美国", birth_date: "1905-07-19", death_date: "1972-02-15", occupation: "记者", biography: "", person_alias: "", person_description: "同P001，埃德加·斯诺", type: "center", colorGroup: "center" },
    { person_id: "P097", name: "邓颖超", nationality: "中国", birth_date: "1904-02-04", death_date: "1992-07-11", occupation: "中国共产党妇女部负责人, 中共中央委员", biography: "", person_alias: "", person_description: "中共妇女部领导，周恩来夫人", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P098", name: "成吉思汗", nationality: "蒙古", birth_date: "1162", death_date: "1227", occupation: "", biography: "其军队曾毁坏保安的古代防御工事", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P099", name: "边", nationality: "", birth_date: "", death_date: "", occupation: "干部", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P100", name: "傅", nationality: "", birth_date: "", death_date: "", occupation: "勤务员", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P101", name: "吉姆·伯特伦", nationality: "", birth_date: "", death_date: "", occupation: "新西兰报人", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P102", name: "武", nationality: "", birth_date: "", death_date: "", occupation: "游击队联络员", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P103", name: "亨利·卢斯", nationality: "美国", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P104", name: "拿破仑", nationality: "法国", birth_date: "1769-08-15", death_date: "1821-05-05", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P105", name: "库图佐夫", nationality: "俄国", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P106", name: "汪精卫", nationality: "中国", birth_date: "1883-05-04", death_date: "1944-11-10", occupation: "政治人物", biography: "", person_alias: "", person_description: "亲日政客，成立南京傀儡政权", type: "opponent", colorGroup: "opponent" },
    { person_id: "P107", name: "伊万斯·卡尔逊", nationality: "美国", birth_date: "1896-02-26", death_date: "1947-05-27", occupation: "美国海军陆战队上校", biography: "", person_alias: "", person_description: "", type: "foreign_friend", colorGroup: "foreign_friend" },
    { person_id: "P108", name: "彭布罗克·斯蒂芬斯", nationality: "", birth_date: "", death_date: "", occupation: "记者", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P109", name: "朱德", nationality: "中国", birth_date: "1886-12-01", death_date: "1976-07-06", occupation: "红军将领", biography: "", person_alias: "", person_description: "红军总司令，与毛泽东共创军队", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P110", name: "亚内尔上将", nationality: "", birth_date: "", death_date: "", occupation: "美国军方将领", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P111", name: "阿奇博尔德·克拉克一卡尔", nationality: "英国", birth_date: "", death_date: "", occupation: "英国驻华大使", biography: "一位自由主义的英国外交官，公开反对法西斯、佛朗哥和日本。", person_alias: "克拉克一卡尔", person_description: "", type: "foreign_friend", colorGroup: "foreign_friend" },
    { person_id: "P112", name: "约翰·亚历山大", nationality: "", birth_date: "", death_date: "", occupation: "英国大使馆秘书", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P113", name: "桑迪诺", nationality: "", birth_date: "", death_date: "", occupation: "游击队领导人", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P114", name: "内维尔·张伯伦", nationality: "英国", birth_date: "", death_date: "", occupation: "英国首相", biography: "", person_alias: "", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P115", name: "佛朗哥", nationality: "西班牙", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P116", name: "亚历山大", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P117", name: "孔祥熙", nationality: "中国", birth_date: "1881-09-11", death_date: "1967-08-16", occupation: "金融官员", biography: "", person_alias: "圣人", person_description: "国民党金融官员，控制战时财政", type: "opponent", colorGroup: "opponent" },
    { person_id: "P118", name: "威廉·亨利·端纳", nationality: "澳大利亚", birth_date: "", death_date: "", occupation: "报人/顾问", biography: "", person_alias: "端纳", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P119", name: "宋查理", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "宋家王朝的真正奠基人", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P120", name: "董显光", nationality: "", birth_date: "", death_date: "", occupation: "国民党战时宣传工作负责人", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P121", name: "陈果夫", nationality: "中国", birth_date: "1892-10-27", death_date: "1951-08-25", occupation: "国民党官员", biography: "", person_alias: "", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P122", name: "陈立夫", nationality: "中国", birth_date: "1900-08-21", death_date: "2001-02-08", occupation: "国民党官员", biography: "", person_alias: "", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P123", name: "宋子文", nationality: "中国", birth_date: "1894-12-04", death_date: "1971-04-25", occupation: "金融官员", biography: "", person_alias: "", person_description: "国民党金融官员，宋家王朝成员", type: "opponent", colorGroup: "opponent" },
    { person_id: "P124", name: "宋霭龄", nationality: "中国", birth_date: "1889-07-15", death_date: "1973-10-19", occupation: "外汇投机者", biography: "", person_alias: "孔祥熙的妻子", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P125", name: "西里尔·罗杰斯", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P126", name: "克拉克·卡尔", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P127", name: "弗兰克·罗伯茨", nationality: "", birth_date: "", death_date: "", occupation: "美国前驻华武官", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P128", name: "马丁·R·尼科尔森", nationality: "", birth_date: "", death_date: "", occupation: "美国驻华财政代表", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P129", name: "戴笠", nationality: "中国", birth_date: "1897-05-28", death_date: "1946-03-17", occupation: "国民党特务头子", biography: "", person_alias: "", person_description: "国民党特务头子，主持秘密警察", type: "opponent", colorGroup: "opponent" },
    { person_id: "P130", name: "弗雷达·厄特利", nationality: "美国", birth_date: "", death_date: "", occupation: "中国问题顾问, 参议院国内安全委员会专家", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P131", name: "约瑟夫·麦卡锡", nationality: "美国", birth_date: "", death_date: "", occupation: "参议员", biography: "", person_alias: "", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P132", name: "蒋鼎文", nationality: "中国", birth_date: "", death_date: "", occupation: "国民党军官", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P133", name: "胡宗南", nationality: "中国", birth_date: "1896-05-12", death_date: "1962-02-14", occupation: "第一军军长", biography: "", person_alias: "", person_description: "", type: "opponent", colorGroup: "opponent" },
    { person_id: "P134", name: "迈克", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "路易·艾黎收养的孩子", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P135", name: "叶挺", nationality: "中国", birth_date: "1896-09-10", death_date: "1946-04-08", occupation: "军人", biography: "", person_alias: "", person_description: "", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P136", name: "项英", nationality: "中国", birth_date: "1898-05", death_date: "1941-03-14", occupation: "军人", biography: "", person_alias: "", person_description: "", type: "china_friend", colorGroup: "china_friend" },
    { person_id: "P137", name: "廖承志", nationality: "", birth_date: "", death_date: "", occupation: "后方联络人员", biography: "", person_alias: "", person_description: "工合后方联络员，共产党干部", type: "other", colorGroup: "other" },
    { person_id: "P138", name: "胡适", nationality: "中国", birth_date: "1891-12-17", death_date: "1962-02-24", occupation: "驻美大使", biography: "", person_alias: "", person_description: "学者，驻美大使，自由主义者", type: "other", colorGroup: "other" },
    { person_id: "P139", name: "W·H·端纳", nationality: "", birth_date: "", death_date: "", occupation: "传教士", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P140", name: "乔·巴恩斯", nationality: "", birth_date: "", death_date: "", occupation: "", biography: "", person_alias: "", person_description: "", type: "other", colorGroup: "other" },
    { person_id: "P141", name: "杨虎城", nationality: "中国", birth_date: "1893", death_date: "1949", occupation: "", biography: "和张学良P013一起发动西安事变", person_alias: "", person_description: "", type: "china_friend", colorGroup: "china_friend" }
];

// 可选：按姓名排序或保留原顺序
// 导出 persons 供其他模块使用（如果使用 ES module）
// if (typeof module !== 'undefined' && module.exports) module.exports = { persons };

// 完整关系数据（约100条）
const relations = [
    // ========== 斯诺相关关系（核心） ==========
    { source: "埃德加·斯诺", target: "毛泽东", relation: "深度采访 / 传记撰写" },
    { source: "埃德加·斯诺", target: "周恩来", relation: "友谊 / 长期联络 / 红区向导" },
    { source: "埃德加·斯诺", target: "宋庆龄", relation: "挚友 / 革命引路人" },
    { source: "埃德加·斯诺", target: "路易·艾黎", relation: "工合合作 / 终生战友" },
    { source: "埃德加·斯诺", target: "鲁迅", relation: "文坛知音 / 编译《活的中国》" },
    { source: "埃德加·斯诺", target: "张学良", relation: "采访 / 西安事变报道" },
    { source: "埃德加·斯诺", target: "蒋介石", relation: "政治对立 / 尖锐批评" },
    { source: "埃德加·斯诺", target: "约翰·本杰明·鲍威尔", relation: "恩师 / 编辑领路人" },
    { source: "埃德加·斯诺", target: "伊万斯·福代斯·卡尔逊", relation: "挚友 / 工合支持 / 红区联络" },
    { source: "埃德加·斯诺", target: "司徒雷登", relation: "同事 / 燕京大学时期" },
    { source: "埃德加·斯诺", target: "黄华", relation: "师生 / 红区翻译" },
    { source: "埃德加·斯诺", target: "张兆麟", relation: "师生 / 一二·九运动策划" },
    { source: "埃德加·斯诺", target: "陈翰伯", relation: "师生 / 一二·九运动支持" },
    { source: "埃德加·斯诺", target: "陆璀", relation: "采访 / 保护" },
    { source: "埃德加·斯诺", target: "俞启威", relation: "相识 / 学生运动指导" },
    { source: "埃德加·斯诺", target: "姚克广", relation: "相识 / 一二·九运动策划" },
    { source: "埃德加·斯诺", target: "龚普生", relation: "相识 / 学生运动支持" },
    { source: "埃德加·斯诺", target: "龚澎", relation: "相识 / 学生运动支持" },
    { source: "埃德加·斯诺", target: "李敏", relation: "相识 / 学生运动联络" },
    { source: "埃德加·斯诺", target: "王汝梅", relation: "师生 / 红区翻译" },
    { source: "埃德加·斯诺", target: "马云汉", relation: "采访 / 华北内幕" },
    { source: "埃德加·斯诺", target: "邓发", relation: "秘密接头 / 红区联络" },
    { source: "埃德加·斯诺", target: "李克农", relation: "接待 / 红区访问安排" },
    { source: "埃德加·斯诺", target: "胡金魁", relation: "陪同 / 苏区旅行向导" },
    { source: "埃德加·斯诺", target: "吴亮平", relation: "翻译 / 毛泽东谈话" },
    { source: "埃德加·斯诺", target: "张闻天", relation: "会面 / 保安欢迎" },
    { source: "埃德加·斯诺", target: "博古", relation: "会面 / 保安欢迎" },
    { source: "埃德加·斯诺", target: "林伯渠", relation: "会面 / 财政部长" },
    { source: "埃德加·斯诺", target: "徐特立", relation: "采访 / 教育部长" },
    { source: "埃德加·斯诺", target: "谢觉哉", relation: "会面 / 司法部长" },
    { source: "埃德加·斯诺", target: "林彪", relation: "采访 / 红军大学校长" },
    { source: "埃德加·斯诺", target: "彭德怀", relation: "采访 / 西部前线" },
    { source: "埃德加·斯诺", target: "贺龙", relation: "听闻故事" },
    { source: "埃德加·斯诺", target: "徐海东", relation: "采访 / 西部前线" },
    { source: "埃德加·斯诺", target: "左权", relation: "会面 / 西部前线" },
    { source: "埃德加·斯诺", target: "聂荣臻", relation: "会面 / 西部前线" },
    { source: "埃德加·斯诺", target: "陈赓", relation: "会面 / 西部前线" },
    { source: "埃德加·斯诺", target: "肖华", relation: "会面 / 西部前线" },
    { source: "埃德加·斯诺", target: "罗瑞卿", relation: "会面 / 西部前线" },
    { source: "埃德加·斯诺", target: "刘志丹", relation: "采访遗孀 / 称颂英雄" },
    { source: "埃德加·斯诺", target: "贺子珍", relation: "相识 / 保安接待" },
    { source: "埃德加·斯诺", target: "同桂荣", relation: "采访 / 拍照" },
    { source: "埃德加·斯诺", target: "蔡廷锴", relation: "采访 / 一·二八抗战" },
    { source: "埃德加·斯诺", target: "蒋光鼐", relation: "采访 / 一·二八抗战" },
    { source: "埃德加·斯诺", target: "翁照垣", relation: "采访 / 闸北巷战" },
    { source: "埃德加·斯诺", target: "张治中", relation: "采访 / 增援上海" },
    { source: "埃德加·斯诺", target: "胡适", relation: "相识 / 抗战期间交流" },
    { source: "埃德加·斯诺", target: "蔡元培", relation: "相识 / 民权保障同盟" },
    { source: "埃德加·斯诺", target: "杨铨", relation: "相识 / 民权保障同盟" },
    { source: "埃德加·斯诺", target: "廖承志", relation: "联络 / 皖南事变信息来源" },
    { source: "埃德加·斯诺", target: "宋子文", relation: "工合国际委员会成员" },
    { source: "埃德加·斯诺", target: "孔祥熙", relation: "工合名义领导 / 批评" },
    { source: "埃德加·斯诺", target: "沃尔特·威廉斯", relation: "师生 / 推荐信" },
    { source: "埃德加·斯诺", target: "吉姆·伯特伦", relation: "同行 / 情报交流" },
    { source: "埃德加·斯诺", target: "史沫特莱", relation: "同行 / 左翼朋友" },
    { source: "埃德加·斯诺", target: "安娜·路易斯·斯特朗", relation: "相识 / 左翼朋友" },
    { source: "埃德加·斯诺", target: "赛珍珠", relation: "相识 / 北平社交" },
    { source: "埃德加·斯诺", target: "乔治·霍勒斯·洛里默", relation: "编辑 / 长期约稿" },
    { source: "埃德加·斯诺", target: "哈里森·史密斯", relation: "出版商 / 预付稿费" },
    { source: "埃德加·斯诺", target: "查利·汤", relation: "文学代理人" },
    { source: "埃德加·斯诺", target: "凯利·格雷厄姆", relation: "朋友 / 财务顾问" },
    { source: "埃德加·斯诺", target: "亨利·卢斯", relation: "合作 / 刊登照片" },
    { source: "埃德加·斯诺", target: "阿奇博尔德·克拉克-卡尔", relation: "合作 / 工合支持" },
    { source: "埃德加·斯诺", target: "约翰·亚历山大", relation: "合作 / 工合筹备" },
    { source: "埃德加·斯诺", target: "威廉·亨利·端纳", relation: "相识 / 西安事变调停" },
    { source: "埃德加·斯诺", target: "乔治·海德姆", relation: "旅伴 / 一同进入红区" },
    { source: "埃德加·斯诺", target: "约瑟夫·F·罗克", relation: "旅伴 / 云南同行" },
    { source: "埃德加·斯诺", target: "奥杰·托德", relation: "采访 / 萨拉齐灌渠" },
    { source: "埃德加·斯诺", target: "英格拉姆医生", relation: "同行 / 灾区防疫" },
    { source: "埃德加·斯诺", target: "甘地", relation: "采访 / 印度会见" },
    { source: "埃德加·斯诺", target: "尼赫鲁", relation: "采访 / 多次会面" },
    { source: "埃德加·斯诺", target: "萨洛吉尼·奈都", relation: "相识 / 印度活动" },
    { source: "埃德加·斯诺", target: "苏哈西妮", relation: "向导 / 孟买参观" },
    { source: "埃德加·斯诺", target: "富兰克林·罗斯福", relation: "三次会见 / 讨论中国政策" },
    { source: "埃德加·斯诺", target: "王牧师", relation: "接头 / 红区联络" },
    { source: "埃德加·斯诺", target: "刘鼎", relation: "护送 / 进入红区" },

    // ========== 中国领导人之间 ==========
    { source: "毛泽东", target: "朱德", relation: "革命战友 / 共同创建红军" },
    { source: "毛泽东", target: "周恩来", relation: "革命战友 / 长期协作" },
    { source: "毛泽东", target: "彭德怀", relation: "革命战友 / 军事指挥" },
    { source: "毛泽东", target: "贺龙", relation: "革命战友 / 长征会师" },
    { source: "毛泽东", target: "林彪", relation: "革命战友 / 红军大学校长" },
    { source: "毛泽东", target: "徐海东", relation: "革命战友 / 红军将领" },
    { source: "毛泽东", target: "刘志丹", relation: "革命战友 / 陕北奠基" },
    { source: "毛泽东", target: "张闻天", relation: "革命战友 / 中央书记" },
    { source: "毛泽东", target: "博古", relation: "革命战友 / 早期领导" },
    { source: "毛泽东", target: "王明", relation: "政治分歧 / 路线斗争" },
    { source: "周恩来", target: "邓颖超", relation: "夫妻 / 革命伴侣" },
    { source: "周恩来", target: "叶挺", relation: "军事协作 / 新四军" },
    { source: "周恩来", target: "叶剑英", relation: "军事协作 / 参谋长" },
    { source: "周恩来", target: "李克农", relation: "情报合作" },
    { source: "周恩来", target: "邓发", relation: "情报合作" },
    { source: "朱德", target: "毛泽东", relation: "革命战友" },
    { source: "朱德", target: "彭德怀", relation: "革命战友 / 上下级" },

    // ========== 宋氏家族与国民党高层 ==========
    { source: "宋庆龄", target: "宋美龄", relation: "姐妹 / 政见分歧" },
    { source: "宋庆龄", target: "宋霭龄", relation: "姐妹 / 关系疏远" },
    { source: "宋庆龄", target: "宋子文", relation: "姐弟 / 有联系但政见不同" },
    { source: "宋美龄", target: "蒋介石", relation: "夫妻 / 政治同盟" },
    { source: "宋美龄", target: "宋霭龄", relation: "姐妹 / 亲密合作" },
    { source: "宋美龄", target: "宋子文", relation: "姐弟 / 财政支持" },
    { source: "宋霭龄", target: "孔祥熙", relation: "夫妻 / 经济同盟" },
    { source: "蒋介石", target: "宋子文", relation: "姻亲 / 财政部长" },
    { source: "蒋介石", target: "孔祥熙", relation: "姻亲 / 行政院长" },
    { source: "蒋介石", target: "陈果夫", relation: "亲信 / CC系" },
    { source: "蒋介石", target: "陈立夫", relation: "亲信 / CC系" },
    { source: "蒋介石", target: "戴笠", relation: "亲信 / 特务首脑" },
    { source: "蒋介石", target: "张学良", relation: "兵谏 / 西安事变" },
    { source: "蒋介石", target: "杨虎城", relation: "兵谏 / 后被杀害" },
    { source: "蒋介石", target: "汪精卫", relation: "政治对手 / 汪投敌后决裂" },
    { source: "蒋介石", target: "胡宗南", relation: "亲信 / 剿共主力" },
    { source: "蒋介石", target: "何应钦", relation: "参谋长 / 对日妥协代表" },
    { source: "蒋介石", target: "蔡廷锴", relation: "政敌 / 十九路军被解散" },
    { source: "张学良", target: "杨虎城", relation: "联合发动西安事变" },
    { source: "张学良", target: "蒋介石", relation: "兵谏 / 后被软禁" },
    { source: "汪精卫", target: "蒋介石", relation: "政治对手 / 投敌后彻底决裂" },
    { source: "汪精卫", target: "日本军国主义者", relation: "投敌 / 建立傀儡政权" },

    // ========== 学生运动领袖之间 ==========
    { source: "黄华", target: "张兆麟", relation: "同学 / 学运同事" },
    { source: "黄华", target: "陈翰伯", relation: "同学 / 学运同事" },
    { source: "黄华", target: "俞启威", relation: "学运 / 上下级" },
    { source: "黄华", target: "姚克广", relation: "学运 / 同事" },
    { source: "张兆麟", target: "陈翰伯", relation: "同学 / 学运同事" },
    { source: "张兆麟", target: "俞启威", relation: "学运 / 接受指导" },
    { source: "俞启威", target: "姚克广", relation: "学运 / 共同策划一二·九" },
    { source: "俞启威", target: "黄华", relation: "学运 / 动员赴苏区" },
    { source: "陆璀", target: "斯诺", relation: "被保护 / 被采访" },
    { source: "龚普生", target: "龚澎", relation: "姐妹 / 学运同事" },
    { source: "龚普生", target: "黄华", relation: "同学 / 学运同事" },

    // ========== 文学界关系 ==========
    { source: "鲁迅", target: "茅盾", relation: "文坛好友" },
    { source: "鲁迅", target: "巴金", relation: "文坛前辈" },
    { source: "鲁迅", target: "萧乾", relation: "文坛前辈" },
    { source: "鲁迅", target: "林语堂", relation: "文坛同辈 / 不同风格" },
    { source: "鲁迅", target: "郁达夫", relation: "文坛好友" },
    { source: "鲁迅", target: "柔石", relation: "学生 / 左联烈士" },
    { source: "鲁迅", target: "冯铿", relation: "学生 / 左联烈士" },
    { source: "茅盾", target: "巴金", relation: "文坛同行" },
    { source: "林语堂", target: "胡适", relation: "同辈 / 自由主义" },

    // ========== 工合运动与外国友人 ==========
    { source: "路易·艾黎", target: "卢广绵", relation: "工合同事" },
    { source: "路易·艾黎", target: "阿奇博尔德·克拉克-卡尔", relation: "工合支持者" },
    { source: "伊万斯·福代斯·卡尔逊", target: "路易·艾黎", relation: "工合支持" },
    { source: "约翰·本杰明·鲍威尔", target: "托姆·密勒", relation: "师生 / 报业继承" },

    // ========== 日军与国民党关系 ==========
    { source: "土肥原贤二", target: "宋哲元", relation: "威逼利诱 / 华北自治" },
    { source: "盐泽幸一", target: "蒋光鼐", relation: "敌对 / 一·二八战争" },
    { source: "植田谦吉", target: "蔡廷锴", relation: "敌对 / 一·二八进攻" },
    { source: "梅津美治郎", target: "何应钦", relation: "签订《何梅协定》" },
    { source: "日本军国主义者", target: "汪精卫", relation: "扶持傀儡" },

    // ========== 美国总统与斯诺 ==========
    { source: "富兰克林·罗斯福", target: "埃德加·斯诺", relation: "三次会见 / 探讨中国政策" },
    { source: "富兰克林·罗斯福", target: "蒋介石", relation: "援助 / 压力促其联共" },
    { source: "尼克松", target: "埃德加·斯诺", relation: "传递访华信息" },

    // ========== 其他重要关系 ==========
    { source: "陈云", target: "斯诺", relation: "化名廉臣写长征记，被斯诺用作附录" },
    { source: "甘地", target: "尼赫鲁", relation: "师生 / 政治传承" },
    { source: "甘地", target: "埃德加·斯诺", relation: "采访 / 尊重其诚实" }
];